### ISSUE TITLE
Extraction fails with Scala 3 ("Can't find ScalaSig")

### ISSUE THREAD

**Issue by charpov** [json4s/json4s#1035]
### json4s version

```
val Json4sNative = "org.json4s" %% "json4s-native" % "4.0.4"
```

### scala version
```
scalaVersion := "3.1.1"
```

### jdk version
```
Java 17.0.2
```

### failure

A type is defined as a case class:
```scala
package ecn

case class OrderRecord(
    stock: String,
    shares: Int,
    price: Option[Int],
    duration: Option[Double]
)
```
This simple test fails:
```scala
package ecn

import org.json4s.native.JsonParser
import org.json4s.DefaultFormats
import org.json4s.jvalue2extractable

object Json {

   implicit val formats: DefaultFormats = DefaultFormats

   def main(args: Array[String]): Unit =
      val json = JsonParser.parse("""{"stock":"C","shares":100}""")
      println(json.extract[OrderRecord])
}
```
with an error:
```
Exception in thread "main" org.json4s.MappingException: Can't find ScalaSig for class ecn.OrderRecord
	at org.json4s.reflect.package$.fail(package.scala:56)
	at org.json4s.reflect.ScalaSigReader$.$anonfun$7(ScalaSigReader.scala:81)
	at scala.Option.getOrElse(Option.scala:201)
        ...
```

**Comment by TomLous** [comment]
I found this issue after figuring out I had a similar error:
https://gitter.im/json4s/json4s?at=62f6032711a6a83d04ef6edc

Any update on a work around or fix?
I wish I could help, but have no idea where to start.

**Comment by plokhotnyuk** [comment]
Yet another workaround is using [jsoniter-scala](https://github.com/plokhotnyuk/jsoniter-scala/). It is [safer](https://github.com/json4s/json4s/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+denial) and [much efficient](https://plokhotnyuk.github.io/jsoniter-scala/) in the runtime with support of `Option` and all Scala collection types out of the box.

Only difference that for each top-level type of message you will need to derive a codec explicitly. It can be done using `derives` (in Scala 3) like [here](https://github.com/plokhotnyuk/jsoniter-scala/blob/7bc5d9b1690506d3c69074c855d3ca6ff7ad8b98/jsoniter-scala-macros/shared/src/test/scala-3/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodeMakerNewKeywordSpec.scala#L37). For cases when source of message definitions cannot be changed `given` definitions can be used like [here](https://github.com/plokhotnyuk/jsoniter-scala/blob/7bc5d9b1690506d3c69074c855d3ca6ff7ad8b98/jsoniter-scala-macros/shared/src/test/scala-3/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodeMakerNewKeywordSpec.scala#L19).

**Comment by gregghz** [comment]
This bug is nearly a year old and I think completely breaks json4s in scala 3 (at least it does for my use case). Are there any plans to address this?

**Comment by gregghz** [comment]
fwiw, it looks like the byte code representation of scala 3 removed the "ScalaSignature" annotation which is required by json4s here https://github.com/json4s/json4s/blob/master/scalap/src/main/scala/org/json4s/scalap/scalasig/ScalaSig.scala#L43

I'm not really sure what this is used for or how to acquire this info otherwise. At a glance (though I'm far from an expert) the byte code looks roughly the same otherwise.

**Comment by gregghz** [comment]
This is still present in scala 3.2.2 and json4s 4.0.6.

**Comment by gregghz** [comment]
here's an easy reproduction case: https://scastie.scala-lang.org/eVhAjdEDQQavMIXRecrQrQ

`case class Thing1(int: Int)` works fine while `case class Thing2(int: Option[Int])` fails with the can't find ScalaSig error.

**Comment by gregghz** [comment]
This is still present in json4s 4.0.6 and 4.1.0-M3 with scala 3.3.0.

**Comment by martin-ockajak** [comment]
The error still occurs in versions `4.0.7` and `4.1.0-M4`. Minimal example to reproduce:

```scala
#!/usr/bin/env -S scala-cli -q
//> using scala 3.3.1
//> using dep org.json4s::json4s-native:4.1.0-M4

import org.json4s.{Extraction, DefaultFormats, Formats}

case class Test(
  value: Option[Int],
)

implicit val formats: Formats = DefaultFormats

Extraction.decompose(Test(Some(0)))
```

**Comment by xuwei-k** [comment]
[4.1.0-M6](https://github.com/json4s/json4s/releases/tag/v4.1.0-M6) released
