### ISSUE TITLE
Support for Map[Symbol, Any]

### ISSUE THREAD

**Issue by velvia** [json4s/json4s#11]
I have some Map[Symbol, Any] that I would like to use json4s to serialize.  Right now only Map[String, Any] is supported.  How hard would it be to add this support, where the Symbol is serialized into a string using symbol.name ?

**Comment by hellokangning** [comment]
Pls try Map[Symbol, JValue], and the convert JValue to any type you want.

**Comment by magnolia-k** [comment]
In the last comment, this issue seems to be resolved, may it be closed?

**Comment by fedeoasi** [comment]
I added support for custom keys in maps in 2014 (https://github.com/json4s/json4s/pull/129), which makes me think that you could create a custom key serializer for symbols, but I haven't tried it.

**Comment by magnolia-k** [comment]
At least the test case for Symbol is working fine, so it seems that the original problem listed in the issue has been solved.

@fedeoasi Thanks for the quick answer, even though it's an old issue

**Comment by magnolia-k** [comment]
This issue will be resolved in the following PR, so I will close it.
If someone has another problem, open another issue

https://github.com/json4s/json4s/pull/129
