### ISSUE TITLE
Multiple EnumSerializers, only last is used.

### ISSUE THREAD

**Issue by phillro** [json4s/json4s#110]
Given multiple EnumSerializers for two differen enums in a case class, the last is always used: https://gist.github.com/phillro/9769301

Is there a way to do a custom serializer just for certain named fields in  a case class? Other work arounds that don't require writing a ull custom serializer covering every field?

**Comment by magnolia-k** [comment]
This issue has already been resolved and will be closed. If you have another problem, please raise another issue.
