### ISSUE TITLE
(fix avail) FieldSerializer improperly serializes lazy vals

### ISSUE THREAD

**Issue by geeksville** [json4s/json4s#111]
Any "lazy vals" in an object show up as null.  Which is not correct, if necessary the val should be generated at the point it is being serialized.

I have a fix for this which I've applied above json4s by writing a custom serializer.  However, I could easily make a pull request which includes the correct fix (making PropertyDescriptor a little bit smarter).

Would you like me to send in a PR?

**Comment by sdiwu** [comment]
Is there any updates on this?

**Comment by geeksville** [comment]
alas - here's my fix, but I haven't had a chance to make a PR: https://github.com/geeksville/json4s/commit/90bed2242983d0ff6c7f29bcd2705a139424c9f2

**Comment by casualjim** [comment]
You know you got it on a branch already. Can't you just hit that button create pull request?. You took the time to link it here?

**Comment by geeksville** [comment]
alas - I haven't done the work to check my change to make sure it works in
all cases.

**Comment by sdiwu** [comment]
@geeksville: could you explain a bit what have you done in the source code? It seems you only put try-catch there ^^

**Comment by sdiwu** [comment]
Hi all, I decided to fix this issue by myself, so here is my fix: https://github.com/json4s/json4s/pull/215

**Comment by geeksville** [comment]
cool beans - yes, I totally agree - my fix must be buried in that branch somewhere.  That's what I get for 'just hitting a button' ;-)

**Comment by magnolia-k** [comment]
This issue has already been resolved and will be closed. If you have another problem, please raise another issue.
