### ISSUE TITLE
Was there ever a version of json4s that worked with Scala 3.0?

### ISSUE THREAD

**Issue by kwalcock** [json4s/json4s#1192]
4.0.6 seems to work with Scala 3.2 and 3.1, but for Scala 3.0(.2) I get these problems:

4.0.2 - TASTy issues
4.0.3 - No Manifest available for Int, etc.
4.0.4 - TASTy issues
4.0.5 - TASTy issues
4.0.6 - TASTy issues

Was there ever a version that worked or is there a work-around for it?

**Comment by xuwei-k** [comment]
- duplicate https://github.com/json4s/json4s/issues/1035
