### ISSUE TITLE
Convert JValue to Map[String, Any]

### ISSUE THREAD

**Issue by lovesh** [json4s/json4s#124]
There should be method to convert the parsed json string to a Map, like most languages have. Right now i have to make a case class and then convert it to a map.

**Comment by jarandaf** [comment]
3.2.11 release seems to be working fine.

**Comment by ziziermao** [comment]
Hey, I still have this problem when trying to do parse(entry).extract[Map[String, Any]]. Any suggestions?

**Comment by ziziermao** [comment]
Hey guys,
 I am trying having this problem when doing
`parse(entry).extract[Map[String, Any]]`
I got:
`org.json4s.package$MappingException: No information known about type`

**Comment by fedeoasi** [comment]
@ziziermao: Extracting a Map[String, Any] works fine for me on the latest version (3.4.0). Could you share the json fragment that you're trying to extract and the version of json4s that you are using?
