### ISSUE TITLE
Make DefaultFormats serializable

### ISSUE THREAD

**Issue by andreaferretti** [json4s/json4s#137]
Instances of `Formats` (in particular `DefaultFormats`) do not implement Serializable.

This means that when using json4s in a distributed setting (Spark or Scalding) one cannot create a global instance of the implicit formats, but instead instances have to be created over and over in each mapper or reducer where it is needed.

In other words, what could be

    class MyJob {
      implicit val formats = DefaultFormats

      someDistributedDataset
      ...
       .map(x => x.extract[Double])
      ...
       .filter(y => y.extract[Int] == 18)

    }

becomes

    class MyJob {
      someDistributedDataset
        ...
       .map({x =>
         implicit val formats = DefaultFormats
         x.extract[Double]
        })
       ...
       .filter({ y =>
         implicit val formats = DefaultFormats
         y.extract[Int] == 18
        })

    }

**Comment by andrassy** [comment]
+!

**Comment by per-kit** [comment]
+1

**Comment by boivie** [comment]
This is rather annoying. Is it difficult to fix?

**Comment by RomanBrodetski** [comment]
+1

**Comment by fousti** [comment]
+1

**Comment by msukmanowsky** [comment]
+1

**Comment by rogaha** [comment]
+1

**Comment by RoyRobertWood** [comment]
Oh god yes please. +1

**Comment by chajath** [comment]
Now with 3.5.3 I see serialization error again with DefaultFormats#dateFormat :

```
Serialization stack:
	- object not serializable (class: org.json4s.DefaultFormats$$anon$4, value: org.json4s.DefaultFormats$$anon$4@7ea19ecb)
	- field (class: org.json4s.DefaultFormats$, name: dateFormat, type: interface org.json4s.DateFormat)
	- object (class org.json4s.DefaultFormats$, org.json4s.DefaultFormats$@7e3e2de0)
	- field (class: sync3k.analytics.CountPerTopic$$anonfun$main$1, name: formats$1, type: class org.json4s.DefaultFormats$)
	- object (class sync3k.analytics.CountPerTopic$$anonfun$main$1, <function2>)
	- field (class: sync3k.analytics.CountPerTopic$$anonfun$main$1$$anonfun$apply$1, name: $outer, type: class sync3k.analytics.CountPerTopic$$anonfun$main$1)
	- object (class sync3k.analytics.CountPerTopic$$anonfun$main$1$$anonfun$apply$1, <function1>)
```

perhaps we should make org.json4s.DateFormat serializable?

**Comment by pferrel** [comment]
+1

I'm still having a similar problem. I've tried upgrading to 3.5.3 but the same happened in 3.2.x (supplied in Spark). Notice I've put DefaultFormats everywhere I could think of. Some of which I don't think need to be serialized.

Here it the code:

        logger.info(s"Creating an RDD for $actionName")
        implicit val formats = DefaultFormats
        val itemProps = df.rdd.map[(ItemID, ItemProps)](row => { <--- error points to this line
          implicit val formats = DefaultFormats
          val itemId = row.getString(0) //
          val correlators = row.getSeq[String](1).toList //corrs [22805,22806]
          (itemId, Map(actionName -> JArray(correlators.map { t =>
            implicit val formats = DefaultFormats
            JsonAST.JString(t)
          })))
        })

Error: 

    Serialization stack:
	- object not serializable (class: org.json4s.DefaultFormats$, value: org.json4s.DefaultFormats$@7fdd29f3)
	- field (class: com.actionml.URAlgorithm, name: formats, type: class org.json4s.DefaultFormats$)
	- object (class com.actionml.URAlgorithm, com.actionml.URAlgorithm@2dbfa972)
	- field (class: com.actionml.URAlgorithm$$anonfun$udfLLR$1, name: $outer, type: class com.actionml.URAlgorithm)
	- object (class com.actionml.URAlgorithm$$anonfun$udfLLR$1, <function3>)
	- field (class: org.apache.spark.sql.catalyst.expressions.ScalaUDF$$anonfun$4, name: func$4, type: interface scala.Function3)
	- object (class org.apache.spark.sql.catalyst.expressions.ScalaUDF$$anonfun$4, <function1>)
	- field (class: org.apache.spark.sql.catalyst.expressions.ScalaUDF, name: f, type: interface scala.Function1)
	- object (class org.apache.spark.sql.catalyst.expressions.ScalaUDF, UDF(input[2, bigint, false], input[3, bigint, false], input[5, bigint, false]))
	- element of array (index: 1)
	- array (class [Ljava.lang.Object;, size 3)
	- field (class: org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10, name: references$1, type: class [Ljava.lang.Object;)
	- object (class org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10, <function2>)
	at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:46)
	at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:295)
	... 128 more
[

**Comment by zhu2856061** [comment]
nice
