### ISSUE TITLE
Add interop for Play! JsValue (enhancement)

### ISSUE THREAD

**Issue by TimPigden** [json4s/json4s#14]
Given the original objective of unifying json implementations It would be great if there was an automatic way of converting to/from the JsValue of Play. And prospect of this?

**Comment by magnolia-k** [comment]
Given the current development status of Json4s, can this issue be closed?

**Comment by TimPigden** [comment]
wow - I forgot this was even here. Haven't touched play in years!
Happy to close. Anyone else care to comment?

**Comment by magnolia-k** [comment]
@TimPigden 

If someone makes a new request, I think it would be more appropriate to open a new issue, so I think it's fine to close it.

**Comment by TimPigden** [comment]
Closing zombie issue
