### ISSUE TITLE
org.json4s.package$MappingException: Can't find ScalaSig for class spray.httpx.marshalling.ToResponseMarshallable$$anon$6

### ISSUE THREAD

**Issue by rinconjc** [json4s/json4s#140]
Strange exception when serializing a nested case class.

```
//given
case class Recipe(title:String,...)
case class Result(code:Int, result:Option[Any]=None, message:Option[String]=None)
// the following fails (see stack trace below)...
path("scrap-recipe"){
  get{
    parameter('url){url=>
      logger.debug(s"extracting recipe from $url")
      complete{
        recipeParser.fromURL(url).map(r => Result(result = Some(r))).
          getOrElse(Result(code = 1, message = Some(s"failed extracting recipe from $url")))            
      }
    }
  }
}
```

Strangely, this works when the complete is returned an explicit value, i.e.:

```
      complete{
        val result = recipeParser.fromURL(url).map(r => Result(result = Some(r))).
          getOrElse(Result(code = 1, message = Some(s"failed extracting recipe from $url")))
        result            
      }
```

Environment:

```
scalaVersion := "2.11.1"

libraryDependencies ++= Seq("io.spray" %% "spray-routing" % "1.3.1",
  "com.typesafe.akka"%%"akka-actor"%"2.3.3",
  "io.spray" %% "spray-can" % "1.3.1",
  "io.spray" %% "spray-client" % "1.3.1",
  "com.typesafe.scala-logging" %% "scala-logging-slf4j" % "2.1.2",
  "io.spray" %% "spray-testkit" % "1.3.1" % "test",
  "org.specs2" %% "specs2" % "2.3.12",
  "org.json4s"   %% "json4s-jackson" % "3.2.10",
  "org.json4s"   %% "json4s-native" % "3.2.10",
  "org.json4s" %% "json4s-ext" % "3.2.10",
  "ch.qos.logback" % "logback-classic" % "1.1.2",
  "org.apache.commons" % "commons-lang3" % "3.3.2"
)
```

Exception 

[info] org.json4s.package$MappingException: Can't find ScalaSig for class spray.httpx.marshalling.ToResponseMarshallable$$anon$6
[info]  at org.json4s.reflect.ScalaSigReader$.findClass(ScalaSigReader.scala:42)
[info]  at org.json4s.reflect.ScalaSigReader$.readConstructor(ScalaSigReader.scala:26)
[info]  at org.json4s.reflect.Reflector$ClassDescriptorBuilder.ctorParamType(Reflector.scala:108)
[info]  at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3$$anonfun$13.apply(Reflector.scala:148)
[info]  at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3$$anonfun$13.apply(Reflector.scala:122)
[info]  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[info]  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[info]  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[info]  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[info]  at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
[info]  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[info]  at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3.apply(Reflector.scala:122)
[info]  at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$constructorsAndCompanion$3.apply(Reflector.scala:116)
[info]  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[info]  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[info]  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
[info]  at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)

**Comment by magnolia-k** [comment]
It is not a Json4s issue, so close it.
