### ISSUE TITLE
Snake support with case classes

### ISSUE THREAD

**Issue by pmincz** [json4s/json4s#146]
Hi!

I want to pass to underscore the case classes when i write json, and pass to camelcase when i read the json to the case classes.

Somebody know how i can do this but with all the case classes?
Implement a custom marshaller?
Someone has an example?

Thanks a lot!!!

**Comment by seratch** [comment]
`Extraction.extract[SomeClass](jackson.parseJson(json).camelizeKeys)` will work for you as demonstrated [here](https://github.com/json4s/json4s/commit/ffc4c9c2411718669bbd4e59f1f2e30502268f98). Let me close this issue now.
