### ISSUE TITLE
The json4s.org web site is rather unusable with Safari 7.0.6 (OS X)

### ISSUE THREAD

**Issue by akauppi** [json4s/json4s#148]
Attached is a screenshot. Problems:
- scrolling the left pane (menus etc.) is not possible (e.g. if not all of it fits in the window) - scroll action is overtaken by the contents to the right
- footer -like links or something is overlaid on top of the menu texts

Just thought to report these.

![nayttokuva 2014-8-28 kello 10 18 48](https://cloud.githubusercontent.com/assets/1297734/4072286/d929c662-2e83-11e4-9b27-32e4daa64085.png)

**Comment by seratch** [comment]
json4s.org pages are changed now. Let me close this issue. If you have any extra feedback, please let us know again.
