### ISSUE TITLE
Please allow writing comments in JSON

### ISSUE THREAD

**Issue by ngocdaothanh** [json4s/json4s#15]
You can make json4s-jackson accept comments in JSON like this:
https://github.com/codahale/jerkson/blob/master/src/main/scala/com/codahale/jerkson/Json.scala#L18

I have JSON files like this and really need to write comments in them:
https://github.com/ngocdaothanh/xitrum-demos/blob/master/config/xitrum.json

**Comment by thefourtheye** [comment]
@casualjim Is there any code example which you can provide? This is pretty common these days and documenting this would be really helpful.
