### ISSUE TITLE
TypeHints don't work in Play When class is from Child classLoader

### ISSUE THREAD

**Issue by meirmaor** [json4s/json4s#162]
We Have an issue when deserializing JSON with typeHints from a Play application
when the deserialized class is from one of our own modules loaded by a class loader which is the grandchild of the classLoader which loaded the json4s jars. 

It fails in ScalaSigReader.resolveClass which get's called with the ClassLoaders paramater
which I can't seem to control and has in it only the one classLoader (which loaded json4s).

resolveClass seems wrong/strange on another front, it's code assumes classLoaders is a List in the way it pattern matches when it actually seems to be wanting to check it's length. The default value is a Vector and goes to the "many" case even though it has a single class loader. 

We have experimented with a fix based on having resolve class always look also at the thread context class loader at the end.
Is there a better way? Would you be receptive to such a pull request? 
Is there a mailing list or somewhere for discussing these stuff or is this the place? (I couldn't find any contribution guidelines)

**Comment by meirmaor** [comment]
This issue was resolved in the 3.2 branch (At the time it was merged into master), but never merged into 3.3

**Comment by seratch** [comment]
>This issue was resolved in the 3.2 branch (At the time it was merged into master), but never merged into 3.3

I just made a pull request #295 to fix this.
