### ISSUE TITLE
sbt.ResolveException: unresolved dependency

### ISSUE THREAD

**Issue by dozed** [json4s/json4s#163]
I get an error during building the master branch:

```
[error] (json4s-examples/*:update) sbt.ResolveException: unresolved dependency: net.databinder.dispatch#dispatch-core_2.9.2;0.11.0: not found
```

According to maven central there is no such build: http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22dispatch-core_2.9.2%22

Can I upgrade dispatch or are there any issues with newer versions?

**Comment by magnolia-k** [comment]
Close the example that already used dispatch-core because it is no longer included in the repository.
