### ISSUE TITLE
How does a case class constructor get chosen in extract?

### ISSUE THREAD

**Issue by vasinov** [json4s/json4s#170]
From the documentation: "Extraction function tries to find the best matching constructor when case class has auxiliary constructors."

How does it actually work? What is "best matching" in this case? Would it be meaningful to provide an option where a primary constructor is forced? E.g., `parse(j).extract[A](primary = true)`.

Thank you.

**Comment by magnolia-k** [comment]
@vasinov 
Yes, using the PrimaryConstructor annotation.

see `tests/src/test/scala/org/json4s/ExtractionBugs.scala`
