### ISSUE TITLE
Is there a `parseFragment` function?

### ISSUE THREAD

**Issue by tkellogg** [json4s/json4s#178]
I want to be able to do this:

``` scala
val JString(foo) = parse("\"foo\"")
val JInt(fortyTwo) = parse("42")
```

but `parse` only works when parsing objects or arrays. I don't propose to change this, but there's still value (to me) in parsing small fragments like strings, numbers, null, objects, arrays -- anything. Would it be easy to add something like this?

**Comment by magnolia-k** [comment]
@tkellogg 

According to RFC8259, JSON is not restricted to objects or arrays.
However, the current native module does not have an RFC8259 compliant parser.

Parsing is possible using the Jackson module.

```scala
scala> import org.json4s._
import org.json4s._

scala> import org.json4s.jackson.JsonMethods._
import org.json4s.jackson.JsonMethods._

scala> parse("true")
res0: org.json4s.JValue = JBool(true)

scala> val JString(foo) = parse("\"foo\"")
foo: String = foo

scala> val JInt(fortyTwo) = parse("42")
fortyTwo: BigInt = 42
```
