### ISSUE TITLE
The default branch should be '3.3'

### ISSUE THREAD

**Issue by seratch** [json4s/json4s#183]
Currently, the default branch is 'master'. But this branch is toward Scala 2.9 builds. And 'scala_2.10' branch is toward Scala 2.11 & 2.10 builds. 

Current status is quite confusing and I guess 'scala_2.10' should be the main development branch now. 

At the very beginning, how about changing the default branch to 'scala_2.10'?

After doing that, I think we should clean up branches.

- rename 'master' to 'scala_2.9'
- rename 'scala_2.10' to 'master'?
- remove other outdated branches

**Comment by seratch** [comment]
I just created the following branches.

- 3.3 <- scala_2.10
- 3.2 <- master

I'd like to set `3.3` as the default branch. Since I don't have permission to access repository settings, I couldn't do that. Would you please do that for me? @casualjim 

After that, if there are no objections, I'll clean up unnecessary branches soon (e.g. scala_2.10, master, scala_2.10* and all others?).

**Comment by casualjim** [comment]
done

**Comment by seratch** [comment]
Thank you for your quick response. And I just removed unused branches.
