### ISSUE TITLE
using replace on List[String] where multiple lists with the same name

### ISSUE THREAD

**Issue by nokka** [json4s/json4s#188]
I'm trying to use replace:
def replace(l : List[String], replacement : JValue)
(http://scala-tools.org/mvnsites/liftweb-2.1/framework/scaladocs/net/liftweb/json/JsonAST/JValue.html)

on a JObject to replace a List with the name "field", the problem is, there's 2 lists with the name "fields" in my JObject. The replace() function doesn't know which one to replace. Is there a way to give it a certain index to replace?

val merged = a.replace(List("fields"), v)

Here's a runnable example of trying to replace values in a JObject, then merge the replaced values back into the original JObject with replace. 

http://pastebin.com/e0xmxqFF

**Comment by magnolia-k** [comment]
@nokka 
There is no way to give an index, so it seems more appropriate to define a method like `replaceArray`.

**Comment by nokka** [comment]
Thanks for the comment, now that's a slow play! 5 years. 😄 I'll close this issue, I've since moved on and I think it's fair to say this has either been solved or has become obsolete.
