### ISSUE TITLE
Extracting a List[_] from JNothing/JNull yields an empty List

### ISSUE THREAD

**Issue by dozed** [json4s/json4s#198]
Example:

``` scala
println(JNothing.extract[List[String]])    // List()
println(JNull.extract[List[String]])       // List()

println(JNothing.extractOpt[List[String]])    // Some(List())
println(JNull.extractOpt[List[String]])       // Some(List())
```

I would have expected that `extract` throws a `MappingException` and `extractOpt` gives `None`.

See: https://github.com/json4s/json4s/blob/3.3/core/src/main/scala/org/json4s/Extraction.scala#L361

**Comment by rossabaker** [comment]
I would have expected the same, but I'm not sure how many people are depending on the current behavior.

**Comment by sriggin** [comment]
Would it be reasonable to deprecate this behavior and throw it behind a flag in `org.json4s.Formats` that defaults to the same behavior? To work around this, we more or less had to replicate `org.json4s.CollectionBuilder` specifically for a `Serializer[Seq]` then added to our formats. 

Hopefully this behavior isn't _expected_ by many people, but I'd love to know why if it is.

**Comment by dozed** [comment]
A `JNothing` is a non-existing value and a `JNull` is neither a primitive nor a collection, it is just null (also see https://github.com/json4s/json4s/pull/96). The current behaviour is clearly incorrect.

I vote to drop it by default. We had a few of those changes in the past relating to optional, missing and null values and releaseing them didnt break the universe. People should read the release notes carefully imo before updating and also have test cases for relevant stuff.

What do you think?

**Comment by mustajarvi** [comment]
Was also bitten by this one. Voting to correct the current behavior.

**Comment by mustajarvi** [comment]
Just to add some more meat to my argument. This is what I expected to hold:

```scala
assert(
  (parse("""
  {
    "nullableKey": {
      "innerKey" : [1, 2, 3]
    }
  }
  """) \ "nullableKey" \ "innerKey").extractOpt[Seq[Int]] == Some(List(1,2,3))
)

assert(
  (parse("""
  {
    "nullableKey": null
  }
  """) \ "nullableKey" \ "innerKey").extractOpt[Seq[Int]] == None
)
```

But instead of getting a `None` when the `nullableKey` is `null` I get a `Some(List())` which was really surprising.

**Comment by danmbyrd** [comment]
:+1:

**Comment by teddyknox** [comment]
:+1:

**Comment by argyakrivos** [comment]
👍

**Comment by kenrose** [comment]
@dozed, am currently being bit by this.  I could take a stab at writing a PR to fix it.

Two options for how to proceed:

  1. Change the behaviour to always throw a `MappingException` on a `null` or missing array (i.e., `JNull` or `JNothing`)
  2. Conditionally change the behaviour based on a value in `Formats` (e.g., `allowNull`)

Which is preferable?

**Comment by jnmoyne** [comment]
+1 on being bit by this, I personally would have expected a `MappingException` (maybe depending on `allowNull` in `Formats`)

**Comment by sumdog** [comment]
:+1: I recently ran into this as well. Looks like it's been open for over a year. Can someone post an example work-around?
