### ISSUE TITLE
Native parser swallow IOException from Reader

### ISSUE THREAD

**Issue by mst-appear** [json4s/json4s#210]
I am using the org.json4s.native.JsonParser(java.io.Reader) method.

If the Reader throws an IOException, the parser gives me a ParseExeption with message "unexpected string end" and no cause. I would expect to get the IOException as cause of this ParseException.

I think the problem is in this method (json4s/native/src/main/scala/org/json4s/native/JsonParser.scala line 214-220):

``` scala
def parseString: String =
  try {
    ParserUtil.unquote(buf)
  } catch {
    case p: ParseException => throw p
    case _ => fail("unexpected string end")              // PROBLEM HERE
  }
```

Line 219 have two problems: it catches every Throwable (it should not catch anything else than an Exception), and it does not report it.

**Comment by magnolia-k** [comment]
In the source as of Json4s 3.7.0-M1, one of the listed problems has been solved because it has been changed to properly catch only NonFatal.

https://github.com/json4s/json4s/blob/7f107237fed487347a234e3b60812294bf5a41af/native/src/main/scala/org/json4s/native/JsonParser.scala#L241-L247
