### ISSUE TITLE
Incompatibility between 3.2.10 and 3.2.11

### ISSUE THREAD

**Issue by mohnishkodnani** [json4s/json4s#212]
Hi, 
I recently am working on a project where I started using 3.2.11. Then I integrated with Apache Spark which probably internally uses 3.2.10.
Once I downgrade to 3.2.10, everything from Spark side works, however, I am using some of the features in 3.2.11
I get the following error when I use 3.2.11 with Apache Spark.
java.lang.NoSuchMethodError: org.json4s.jackson.JsonMethods$.render(Lorg/json4s/JsonAST$JValue;)Lorg/json4s/JsonAST$JValue;

The Spark Code is calling def json: String = compact(render(jsonValue))

I checked the tags on the json4s jackson git repo and it seems in 3.2.11 the render function is taking implicit parameters for Formats which it wasnt in 3.2.10.

Is this a known issue. Shouldnt the API is compatible between minor versions ?

thanks
mohnish

**Comment by NikitaPanteleev** [comment]
I encountered this problem too. Thx for the hint to downgrade to 3.2.10!

**Comment by H4ml3t** [comment]
You saved my life, thank you very much. Do you think in next release it will be solved?

**Comment by alexanderdean** [comment]
Thanks so much for posting this!

**Comment by foovungle** [comment]
Thank you also! I spent an hour trying to figure this one out!

**Comment by nicky-zs** [comment]
I also met this problem using json4s-jackson 3.2.11 with spark 1.3.1 on scala 2.10.4.
Thank you so much for the downgrade hint.

**Comment by seratch** [comment]
Since incompatibility between 3.2.10 and 3.2.11 was a pain for many developers, we're going to use MiMa since 3.3.0 as proposed [here](https://github.com/json4s/json4s/issues/225). Let me close this issue now.

**Comment by DoubleFaults** [comment]
Thank you for your hint,  you saved my life

**Comment by hellokangning** [comment]
Thank you, I just met this bug

**Comment by ericxsun** [comment]
Thank you for your hint, you saved my life
