### ISSUE TITLE
Scalap error: not a valid class file

### ISSUE THREAD

**Issue by raimohanska** [json4s/json4s#216]
With Java 1.8.0_20 and above on OSX I get the following error:

```
scala.tools.scalap.scalax.rules.ScalaSigParserError: Unexpected error: Not a valid class file
    at scala.tools.scalap.scalax.rules.Rules$$anonfun$expect$1.apply(Rules.scala:76)
    at scala.tools.scalap.scalax.rules.scalasig.ClassFileParser$.parse(ClassFileParser.scala:97)
...
```

This seems to occur only when _debugging_, i.e. when run with params like `-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044`.

It occurs when trying to serialize quite simple case classes. 

The sad thing is I cannot provide a reproduction package, because the issue seems very sensitive to conditions; I cannot reproduce it with a simple piece of code. I have only been able to have it occur when my full Jetty stack is up. 

When debugging this more closely I found that the actual class whose parsing fails varies run-to-run, so it's not specific to a certain class file. Also it actually succeeds some times provided some fortunate timings facilitated by breakpoints here and there.

I've spent a day trying different scala versions and modding my application code etc and trying to make a reproduction package. Really sorry for not succeeding in that.

**Comment by raimohanska** [comment]
It seems to work with 8u40 Build b23 available at https://jdk8.java.net/download.html. So, fix is on the way.

**Comment by timothy-kim** [comment]
I've ran into same issue while serializing case classes. I can confirm that the issue goes away when removing debug parameter.

**Comment by timothy-kim** [comment]
And I just confirmed that upgrading to Java 8u40 seems to remedy the issue.

**Comment by raimohanska** [comment]
@timothy-kim we found out that there's a workaround for pre-u40 jre's too: use the `-XX:-EliminateAutoBox` option. Here's the JRE issue btw: https://bugs.openjdk.java.net/browse/JDK-8058847
