### ISSUE TITLE
Change serialization of Seq[Option[T]] so it doesn't remove elements

### ISSUE THREAD

**Issue by zszugyi** [json4s/json4s#23]
Changing the length of an array during serialization seems to be pretty unexpected and
probably undesired in a lot of cases.

For example:
scala> val a: List[Option[Int]] = List(Some(1), None, None, Some(1))
scala> render(a)
res14: org.json4s.package.JValue = JArray(List(JInt(1), JNothing, JNothing, JInt(1)))
scala> compact(render(a))
res15: String = [1,1]

This would be much better serialized to [1, null, null, 1] or [1, undefined, undefined, 1]

**Comment by seratch** [comment]
EmptyValueStrategy.preserve introduced by #131 works fine as expected here. Let me close this issue after 2 years.
