### ISSUE TITLE
Is there any way to prevent serilizing private fields？

### ISSUE THREAD

**Issue by ImNotMyself** [json4s/json4s#239]
It seems the https://github.com/json4s/json4s/blob/9e1de4ad03b5aa24153bf91e4722a7fd538f51f8/core/src/main/scala/org/json4s/Extraction.scala#L114
will reflect all the fields from the instance's class, no matter private or not and thus all the fields will be exposed by default.

Sample:

``` scala
import org.json4s.DefaultFormats
import org.json4s.jackson.Serialization._
import org.json4s.FieldSerializer

case class Test(private val myPriVal:String)
implicit val formats = DefaultFormats + FieldSerializer[Test]()

write(Test("HelloWorld")) //res0: String = {"myPriVal":"HelloWorld"}
```

My question is, Is there any way to prevent serilizing private(or protected) fields ?

The only way I found is filtering the field by name as below. But this may become ugly once there are lots of private fields inside the class and we want to prevent them to be exposed.

``` scala
import org.json4s.DefaultFormats
import org.json4s.jackson.Serialization._
import org.json4s.FieldSerializer

case class Test(private val myPriVal:String)
import org.json4s.FieldSerializer._
implicit val formats = DefaultFormats + FieldSerializer[Test](serializer = ignore("myPriVal"))

write(Test("HelloWorld")) //res0: String = {}
```

I need your advise

**Comment by magnolia-k** [comment]
Unfortunately, Json4s does not provide a way to remove only private fields.

Once this issue is closed, if there is a request from another person, we will reopen it to continue discussing whether to extend it.
