### ISSUE TITLE
Some scalaz examples in README do not work

### ISSUE THREAD

**Issue by greenrd** [json4s/json4s#240]
The README for the scalaz module says:

    implicit def addrJSONR: JSONR[Address] = Address.applyJSON(field("street"), field("zip"))

But such code without type parameters doesn't compile.

The similar examples in `tests/src/test/scala/org/json4s/scalaz/Lotto.scala` were commented out years and years ago, and indeed when they are uncommented they don't compile either.

**Comment by seratch** [comment]
I myself don't use json4s-scalaz module at all. Is there anyone who is interested in fixing this?

**Comment by xuwei-k** [comment]
```scala
implicit def addrJSONR: JSONR[Address] =
  Address.applyJSON(field[String]("street"), field[String]("zip"))
```
