### ISSUE TITLE
List must be wrapped in JArray instead JObject

### ISSUE THREAD

**Issue by ilyakhov** [json4s/json4s#241]
```
pretty(render(JObject("A" -> (parse("""{}""") \ "anything").transform {
  case JNothing => Nil
})))

pretty(render(JObject("A" -> (parse("""{}""") \ "anything").transform {
  case JNothing => JArray(Nil)
})))
```

Output:
```
res0: String = {"A":{ }}
res1: String = { "A":[]}

```

The res1 looks more reasonable for 1st case, but instead we have res0. Will you change this behaviour?

**Comment by seratch** [comment]
IMO, Scala's `Seq` doesn't represent JSON array type in json4s. So this change won't be reasonable.

**Comment by seratch** [comment]
Let me close this issue. If you have any extra feedback, please let us know again.
