### ISSUE TITLE
case class extract does not work

### ISSUE THREAD

**Issue by ShengC** [json4s/json4s#252]
Unless I misread the faq, what happens to the case class extract is exactly the opposite. If I define case class in repl, I can extract it, but not in the code. Note this is a problem in 3.x, but not in 2.x

```
  import org.json4s._
  import org.json4s.native.JsonMethods._
  
  implicit val format = DefaultFormats
  
  case class Person(name: String, age: Int)
  val json = """{"name":"joe","age":15}"""
  
  println(parse(json).extract[Person])
```

```
[error] (run-main-18) org.json4s.package$MappingException: Parsed JSON values do not match with class constructor
[error] args=
[error] arg types=
[error] constructor=public Foo$Person(java.lang.String,int)
org.json4s.package$MappingException: Parsed JSON values do not match with class constructor
args=
arg types=
constructor=public Foo$Person(java.lang.String,int)
```

**Comment by yuganghu** [comment]
Why close it? I have the similar problem (json4s-jackson_2.11-3.2.10.jar) not in REPL. What did you do to fix it?

**Comment by yuganghu** [comment]
case class Person2(name: String)
  test("Test json extraction - Person2 ") {
    import org.json4s._
    import org.json4s.jackson.JsonMethods._
    implicit val formats = DefaultFormats
    var json1 = parse("""{ "name": "joe" }""")
    val name = (json1 \ "name").extract[ String ]
    println(name)
    // Mapping Exception
    //val address = (json \ "address").extract[String]
    //println("address=" + address)
    val person = json1.extract[ Person2 ]
    println(person);
  }

**Comment by yuganghu** [comment]
Looks like 3.2.11 fixed it.
