### ISSUE TITLE
Support Scala.js

### ISSUE THREAD

**Issue by mdedetrich** [json4s/json4s#256]
Complications
1. Need to remove all reflection, replace it with Macros
2. Semantic differences between js and JVM (BigDecimal, floats) need to be accounted for

Why?

`Json4s` in my opinion is still the superior API for working with JSON for Scala. It gives you incredible flexibility in regards to how much control the programmer has in querying JSON (you can be as strict or as loose you need to). Its a shame its not available on ScalaJS

Apologies if there isn't already a task for this

**Comment by Fristi** [comment]
`Need to remove all reflection, replace it with Macros` or use shapeless to derive typeclasses for `Writer/Reader`

**Comment by mdedetrich** [comment]
The new json4s ast already works on Scala.js (you can find it here https://github.com/json4s/json4s-ast), its just that json4s (which would probably be a new major) needs to be built ontop of it

There is a slight roadblock in regards to it getting approved by the SLIP process, need to actually have a look at this

**Comment by dozed** [comment]
Here is a cross-build for json4s-ast: https://github.com/dozed/json4s/commit/04e7486d68c584506bf3f0dec648c20f40aa0017

**Comment by mdedetrich** [comment]
@dozed Also letting you know that the final draft for scala-json-ast (which is based on the old reboot of json4s ast) is at its final stages for a draft, you can see it here https://github.com/mdedetrich/scala-json-ast

**Comment by andwxh** [comment]
Does json4s will support Scala.js in the future?
There is still nothing as good as json4s in Scala.js

**Comment by mkotsbak** [comment]
Last time I tried json4s it was very reflection heavy. That needs to be removed or wait for the experimental reflection support for Scala.Js to progress.

**Comment by a1russell** [comment]
FYI, Scala.meta recently merged support for Scala.js (see https://github.com/scalameta/scalameta/pull/761). Hopefully there's enough there to replace the reflection in json4s.

**Comment by magnolia-k** [comment]
Since the discussion of this issue has stopped, it will be closed once. Reopen if you have any issues to discuss.
If reflection needs to be reworked, isn't it a new library?
