### ISSUE TITLE
OSGi-friendly support

### ISSUE THREAD

**Issue by briantopping** [json4s/json4s#26]
Just trying to get some code from "Scalatra in Action" running under OSGi and notice that there are no OSGi manifest entries in the jars.  Using Pax URL is difficult to do with the "wrap" protocol because there are packages duplicated across jar artifacts.  

I'd be happy to help get the artifacts restructured, but there has to be some interest.  Anyone?

**Comment by briantopping** [comment]
Wow, i filed this issue and forgot. Sorry about that, folks.

I'd be happy to crank this out, but it sounds like there's a major version number change necessary first.

**Comment by PhilAndrew** [comment]
Please OSGi.

**Comment by magnolia-k** [comment]
There is no plan for OSGi support for Json4s at this time, so this issue will be closed once.

If you have a strong request, open the issue again.
