### ISSUE TITLE
Unable to Serialize Java 8 LocalDateTime fields.

### ISSUE THREAD

**Issue by wpoosanguansit** [json4s/json4s#271]
I have imported JavaTimeSerializers I found https://github.com/DanielaSfregola/json4s/blob/3.3/ext/src/main/scala/org/json4s/ext/JavaTimeSerializers.scala

However, the date fields are still not being rendered at all.  How do we serialize and deserialize Java 8 LocalDateTime?  Thanks for your help.

**Comment by seratch** [comment]
Built-in serializer/deserializer doesn't support Java8 Date and Time API yet. See this PR https://github.com/json4s/json4s/pull/243 and you can put them into your project. They should work.

**Comment by wpoosanguansit** [comment]
Thanks for your help.  I saw that and had it in my project.  For some reasons, it did not work.  I am not quite sure why.  So I had to do it manually for now.  Thanks again.

**Comment by tcrossland** [comment]
Does 3.4 implement support for `java.time._` date/time types? I can't find any commit which implements this. Should the ticket be reopened?

Thanks
