### ISSUE TITLE
New Json4S-AST module (with breaking changes)

### ISSUE THREAD

**Issue by mdedetrich** [json4s/json4s#272]
After a discussion with @rossabaker on gitter, we broadly agreed on the following things
1. The current `JSON4s` has an API which dates back to 2008, and has a lot of things which could be improved
2. The `JSON4s` API should be in its own module. In my opinion, I think we should have it strictly as a new github repo (still under `json4s`), mainly because it provides the impression that the API is stable and will almost never change, plus it makes it easier for other libraries/frameworks to integrate with Json4s, however making the `json4s-api` as a separate sbt module also works. This should definitely be discussed.

Here is a current list of breaking API changes that we came up with (obviously up for disucssion)
1. Change `JArray(List[JValue])` to some other collection which has O(1) access. The question is, do we want to enforce this fully? There is still merit in using `List`, because it takes up the lowest amount of memory for sequential access (only exception would be `Array`)?.
   We could make it `JArray(Seq[JValue])` which just enforces you have some sequence, and then its up to the caller to dictate how its constructed. `JArray(IndexedSeq[JValue])` means that you enforce collections with O(1) access, which may take more memory than desired (in some cases)
2. Change `JObject(List[JField])` to `JObject(Map[String, JValue])`. I dont think there is much disagreement about this change in regards to improving the API. Personally, dealing with `List[JField]` has been really annoying on my end, and having it as a `Map` makes a lot more sense.
3. Remove `JNothing`. Personally I have used `JNothing` in our code legitimately (have to double check this, there may be a smarter way that didn't involve `JNothing`), however there are strong arguments that it should be removed, as its essentially a `null` (albeit a bit safer because its restricted to just `JSON4s`). Havn't had practical issues due to `JNothing` existing, but as @rossabaker said, it is smelly
4. `JBool` is currently a case class (i.e. `case class JBool(value: Boolean)`, however @rossabaker  thinks it should be a sealed class with 2 values. Not sure what advantage this would give, mind explaining @rossabaker ?

Other things we could explore, such as making `JValues` a value class (i.e. `AnyVal`) for certain values (such as `JBool`) for performance (if possible), and anything else people can come up with?

This is also a continue on from https://github.com/json4s/json4s/issues/3

**Comment by casualjim** [comment]
I have to just chime in here, do what you want. But be aware that json4s is used by 1000's of people. Breaking changes come at a very high cost globally. 

So please do take that in consideration. that's my 2c

**Comment by mdedetrich** [comment]
Definitely agreed, with https://github.com/json4s/json4s/issues/256 I didn't want to do any breaking API changes, but there is an argument for fixing obviously glaring problems (`JObject` is one that comes to mind)

Json4s 4.x could support both API's, there is nothing really preventing that, so people have an option that won't break their code

**Comment by rossabaker** [comment]
I have argued against breaking changes when proposed in the past (e.g., #3), but I also have felt a lot of pain over the years from AST choices inherited from lift-json, to the point I'm moved to consider other libraries.

Constructors of the old AST could be preserved.  I don't see how extractors would, short of rebooting the project into a new package name.  A "v4" in the package name could allow more guiltless refactoring, though `org.json4s.v4` is unsightly.  

On to the points:

1. `Seq` permits mutable collections.  `scala.collection.immutable.Seq` supports tradeoffs between linear and indexed sequences, but is little used and likely to cause endless compiler error confusion.  I like the idea of it being based on a `Vector`.  (Prior art: spray-json)

2. Preservation of insertion order is lost with a Map, but the spec calls it an unordered collection.  (Prior art: play-json, spray-json)

3. I have crashed many times trying to render a `JNothing`.  play-json recently made a [similar change](https://github.com/playframework/playframework/blob/5b9a913fcb14c36c1fd262fcaeb39b54ad54fd22/documentation/manual/releases/migration24/Migration24.md#json-api-changes).  Other libraries get by fine without any undefined value at all.  The play-json compromise seems a bit ad hoc to me, but I'd be interested to see code impact before condemning it.

4. There are only two possible values of `JBoolean`, so it doesn't make sense to create a bunch of case class wrappers for each instance.  I think [spray-json gets this just right](https://github.com/spray/spray-json/blob/v1.3.2/src/main/scala/spray/json/JsValue.scala#L106-L118).

5. I'm skeptical of all the concrete `JNumber` types.  `JDouble`, `JDecimal`, and `JInt` have no meaning in the JSON spec, and complicate pattern matching.  What's wrong with a `case class JNumber(BigDecimal)`?

**Comment by casualjim** [comment]
https://github.com/json4s/json4s-ast/blob/master/src/main/scala/org/json4s/ast/JValue.scala

There is also that project

**Comment by rossabaker** [comment]
Interesting.  I overlooked that one entirely in favor of the json4s-ast module in the main repo.  The `org.json.ast` package is an opportunity to put the breaking AST in a different package, though it would add an import tax to any practical usage of the core.

**Comment by mdedetrich** [comment]
> Constructors of the old AST could be preserved. I don't see how extractors would, short of rebooting the project into a new package name. A "v4" in the package name could allow more guiltless refactoring, though org.json4s.v4 is unsightly.

We can probably specify a better name, like `json4s.reboot.api` vs `json4s.api` or something like that? I don't think we should tie the new API to `v4` of JSON4s.

I do think killing the API is a bit harsh (although nothing is forcing people to upgrade), but at the same time I think this is the best time to do a breaking change.

> Seq permits mutable collections. scala.collection.immutable.Seq supports tradeoffs between linear and indexed sequences, but is little used and likely to cause endless compiler error confusion. I like the idea of it being based on a Vector. (Prior art: spray-json)

By `Seq`, I did mean the immutable version, however could you elaborate on the compiler confusion you are talking about? I am leaning towards `immutable.Seq`, mainly because there are (some) legitimate reasons for using a `List` (mainly somewhat personal, I have to work with gigs of JSON data, and `Vector` does take up more memory than `List`, especially if the size of the collection is small, which adds up if you have a lot of `JArray`'s). Not going to throw a fit if we choose `Vector` though

> Preservation of insertion order is lost with a Map, but the spec calls it an unordered collection. (Prior art: play-json, spray-json)

Non issue if we strictly follow `JSON` spec, but there may be other implementations where this may be a problem (i.e. `Binary JSON` for Mongo, maybe `JSON`/`JSONB` for postgres)? In the worst case scenario, Scala does have an ordered map type (`collection.SortedMap`)

 > I have crashed many times trying to render a JNothing. play-json recently made a similar change. Other libraries get by fine without any undefined value at all. The play-json compromise seems a bit ad hoc to me, but I'd be interested to see code impact before condemning it.

I will find the usages in my code base to see if there are applicable usages. Just to reiterate, this may be more likely just a personal attachment due to how our code is run, don't have any inherit issue in removing `JNothing`.

> There are only two possible values of JBoolean, so it doesn't make sense to create a bunch of case class wrappers for each instance. I think spray-json gets this just right.

I think this is more of a design choice. Having it as a `case class` has merit in that all `JValue`'s are represented as `case classes`, which makes it very easy to serialize/deserialize, as well as create macros for them. If we also intend to use `AnyVal`, then using a single `boolean` in the `case class` will have better performance due to not boxing. 

I have a personal aversion to doing stuff like

```scala
json match {
    case JTrue =>
    case JFalse =>
}
```
versus
```scala
json match {
    case JBool(b) if b =>
    case JBool(b) if !b =>
}
```

Although you can obviously use the `JBool`'s unapply method so you can match what is happening in the latter example, I see it as an unnecessary abstraction. If you create concrete types for what are essentially bools, it becomes unclear as to how you should treat the boolean (should I use the `object` types, or should I use the JBool's unapply?). Not entirely convinced on this one.

> I'm skeptical of all the concrete JNumber types. JDouble, JDecimal, and JInt have no meaning in the JSON spec, and complicate pattern matching. What's wrong with a case class JNumber(BigDecimal)?

`JDouble`/`JDecimal` definitely should be removed in favor of having just a `BigDecimal`. `JSON` spec mandates that all numbers have unlimited potential precision, and there is also no `Int` type. There is no separation between `Int`/`Rational` numbers (either in `Javascript` or `JSON`), so the separation in `JSON`'s is mainly convenience. It allows us to easily tell if a number is an Int, which is used quite often (i.e. your standard `id`).

The thing is, detecting if a `BigDecimal` is an int is quite verbose (if you want to take into account failure), and this scenario is **incredibly** common. So long story short, a `JNumber`/`JInt` separation is incredibly convenient, albeit doesn't mirror the spec exactly. What do people think?

**Comment by casualjim** [comment]
dropping undefined from a json library is going to bite very hard if you want to support jsonschema etc.

Undefined represents the absence of a key vs the absence of a value. This is important, if you want to stand a chance implementing something like swagger v2 with json4s

**Comment by mdedetrich** [comment]
Yeah, I think the reason why we use `JNothing` is along those lines (in our case, its with `postgres`'s `JSON`/`JSONB` type)

**Comment by mdedetrich** [comment]
In regards contribution, I may just fork https://github.com/json4s/json4s-ast, and add another branch for prototyping the new AST and submit as a pull request, once we have decided what changes we should go with

**Comment by rossabaker** [comment]
> By Seq, I did mean the immutable version, however could you elaborate on the compiler confusion you are talking about? I am leaning towards immutable.Seq, mainly because there are (some) legitimate reasons for using a List (mainly somewhat personal, I have to work with gigs of JSON data, and Vector does take up more memory than List, especially if the size of the collection is small, which adds up if you have a lot of JArray's). Not going to throw a fit if we choose Vector though

Vector is a big win over List for memory on large collections.  I don't know about small, but I'm guessing you're right.

The confusion is not as bad as I imagined last night.  It will be a problem when a user naively attempts to create a `JArray` from a `Seq`, without realizing it's a different `Seq` than the one in `Predef`.

```scala
scala> case class JArray(values: scala.collection.immutable.Seq[JValue]) extends JValue
defined class JArray

scala> case class JString(s: String) extends JValue
defined class JString

scala> JArray(List(JString("a"), JString("b")))
res0: JArray = JArray(List(JString(a), JString(b)))

scala> JArray(Vector(JString("a"), JString("b")))
res1: JArray = JArray(Vector(JString(a), JString(b)))

scala> JArray(Seq(JString("a"), JString("b")))
<console>:13: error: type mismatch;
 found   : Seq[JString]
 required: scala.collection.immutable.Seq[JValue]
              JArray(Seq(JString("a"), JString("b")))
                        ^

scala> val JArray(Seq(a, b)) = res0
a: JValue = JString(a)
b: JValue = JString(b)
```

Another difference between Vector and Seq is that List-extractors will work for some legacy code and fail at runtime for others.  A Vector declaration is a more breaking change, but one that would lead to safer extractors.
 
```scala
scala> val JArray(a :: b :: Nil) = res0
a: JValue = JString(a)
b: JValue = JString(b)

scala> val JArray(a :: b :: Nil) = res1
warning: there were 1 feature warning(s); re-run with -feature for details
scala.MatchError: JArray(Vector(JString(a), JString(b))) (of class JArray)
```

> Non issue if we strictly follow JSON spec, but there may be other implementations where this may be a problem (i.e. Binary JSON for Mongo, maybe JSON/JSONB for postgres)? In the worst case scenario, Scala does have an ordered map type (collection.SortedMap)

`SortedMap` would provide a defined order, but not necessarily preserve insertion order.  Argonaut has a specific type for fast lookup and insertion-preservation, though I'm still not aware of a use case that requires the latter.

> I think this is more of a design choice. Having it as a case class has merit in that all JValue's are represented as case classes, which makes it very easy to serialize/deserialize, as well as create macros for them. If we also intend to use AnyVal, then using a single boolean in the case class will have better performance due to not boxing.

`JTrue` and `JFalse` would be case objects -- it's still cases all the way down.  I agree that `JBool` would have an `unapply`.

Once you treat the `JBool` as a `JValue`, it's going to box, no?  `AnyVal` is *very* restrictive in what prevents boxing.

> The thing is, detecting if a BigDecimal is an int is quite verbose (if you want to take into account failure), and this scenario is incredibly common. So long story short, a JNumber/JInt separation is incredibly convenient, albeit doesn't mirror the spec exactly. What do people think?

I think that's an issue for formats rather than the AST.  The `Int` reader would match `case bd: JNumber(bd) if bd.isValidInt => Yep(bd.toInt); case _ => Nope`.  (Representation of `Yep` and `Nope` is a discussion for the formats replacement.)

> dropping undefined from a json library is going to bite very hard if you want to support jsonschema etc.

> Undefined represents the absence of a key vs the absence of a value. This is important, if you want to stand a chance implementing something like swagger v2 with json4s

I don't mind `JNothing`'s existence as much as I mind it being a `JValue`, which breaks the totality of serialization.  If there's a sane sum type for `JValue | JNothing` -- and I don't know what to call it -- I would drop my objection.

**Comment by bryce-anderson** [comment]
Drive by comment: I think @rossabaker mentioned that getting back the the original json4s goal of 'one AST' is probably the single best thing that could happen. Has there been any contact with the other significant JSON libraries about this? I know the [spray folks were at one point interested in this](https://github.com/json4s/json4s/issues/3) but it never seemed to materialize. It might even be worth it to just adopt an AST from an active project if they are willing to split it out into a bare package. Without achieving that goal this will become Yet Another  JSON Library except it will be far more ironic considering the json4s original goal...

**Comment by bryce-anderson** [comment]
As a follow up drive by comment: the [Spray AST](https://github.com/spray/spray-json/blob/master/src/main/scala/spray/json/JsValue.scala) has essentially all the properties that have been so far described as desirable: Bool case objects, one number type based on `BigDecimal`, `Map` based JObjects, `Vector` backed JArrays...

**Comment by rossabaker** [comment]
I think spray-json's AST is right on the mark, with these two outstanding issues:

* The methods on `JsValue` couple it to spray-json's codec and a partial method (`asJObject`).  These are both fine for that library, but outside the spirit of a bare AST.

* It has no concept of `JNothing`.  If json4s still benefits from a `JNothing`, it would make sense to introduce that in json4s-core.  The downside is that `JValue` would have to be wrapped in the sum type that unifies it with `JNothing`.

If it would get other projects on board, and we can resolve the above, I'd sign onto using Spray JSON as the basis.

**Comment by mdedetrich** [comment]
Just letting you guys know, I have forked https://github.com/json4s/json4s-ast and I have done the following changes, which (so far) seem to address the issues. The fork is here, in a branch named reboot https://github.com/mdedetrich/json4s-ast/tree/reboot

As a heads up, I am following the original formats of the `json4s-ast` as designed by @casualjim , mainly because at the time, @casualjim was in communications with people from `spray`,`typesafe` and `play` about a general AST (so I am using the assumption that the latest version of `json-ast` somewhat resembles what they had in mind). The `json4s-ast` had some things added on to what we are discussing (and hence these things remain), such as

1. varargs apply methods for things like JArray, letting you do JArray(JString("a")) instead of having to do JArray(Vector(JString("a"))
2. Format conversions for BigDecimal to other formats. This has been retained, but has been converted to a more Scala idiomatic interface (uses the `.to[T]` interface). I think a discussion still needs to be had about whether these formats should stay there. `JNumber` will still only ever contain a `BigDecimal`

In my fork, here are the following changs I have done

1. JArray is `JArray(immutable.Seq), however there is an added apply method that goes from `predef.Seq` to `immutable.Seq`). This means you can do `JArray(Seq(JString("a"),JString("b")))` and by default, it will construct a `Vector`
2. Changed `JBool` to `JBoolean` (I want to try and at least have the naming the same as the current AST), as well as changed it to case objects. I have used the `Spray` implementation that @rossabaker mentioned earlier, however I have done some changes. The `def`'s has been converted to `val`'s (for performance, plus I also don't know of any use case as to why it should be a `def`), `apply`/`unapply` methods have been inlined, and `unapply` now returns a `Boolean` instead of an `Option[Boolean]` (also not sure why it returned an `Option[Boolean]`, can someone expand here).
3. Inlined many apply methods for performance (need to double check this, I think it should be fine)
Also, `JNothing` still exists as a `JValue`, I believe we need to explore how best to implement it. I think most people agree that it is required in some form

What would likely be a controversial discussion would be `BigDecimal` format converters and whether that should be in the AST or not. As always, there are pros and cons. Having the converters in there means
1. Using the bare AST is incredibly easy (and this will be enforced, since its the bare AST)
2. We are mandating that he AST needs to convert to certain formats, which means other libraries which use the AST know that there will be predefined methods that go from `BigDecimal` to `Int`. I can see this being useful for things like streaming (i.e. `BigDecimal` to `Byte` or `ByteArray` converters)

Don't have any qualms in removing from the AST if it prevents it from getting adopted/is a bad design decision. I am however re-iterating that it was there originally, so it may have been something that the other libraries/frameworks/stakeholders wanted (@casualjim probably needs expand on this)

@bryce-anderson, there was a private conversation regarding getting a bare json4s-ast to be adopted by typesage, I would contact @casualjim about it

**Comment by rossabaker** [comment]
Thanks for this!  I already left a barrage of comments on the pull request.  I'd suggest json/json4s-ast#1 is the best place to discuss the technical side of this, now that there is real code to discuss, and it can be organized by lines instead of massive comments.

**Comment by kag0** [comment]
Not sure if this initiative is dead (considering the 3 year old issue), but I figured I'd throw a comment in here anyway.

If you do remove `JNothing`, consider changing `Reader` and `Writer` to operate on `Option`s like
```scala
trait Reader[T] {
  def read(value: Option[JValue]): T
}
trait Writer[-T] {
  def write(obj: T): Option[JValue]
}
```
This makes it easier to implement subtle distinctions between null and absent values. For example custom behavior for `Option`, or supporting an algebraic data type for HTTP PATCH (`None` would be `Ignore`, `JNull` would be `Delete`) like 
```scala
sealed trait Patch
case class Update[A](value: A) extends Patch
case object Ignore extends Patch
case object Delete extends Patch
```

**Comment by magnolia-k** [comment]
There are no plans to rebuild the Json4s AST at this time, so this issue is closed for now.

If we rebuild the AST, it will no longer be Json4s, it will be a new JSON module :)

When new discussions are needed, please reopen it again.
