### ISSUE TITLE
Upcoming 3.3.0 release plan

### ISSUE THREAD

**Issue by seratch** [json4s/json4s#286]
I'd like to tell you my opinion on the 3.3.0 release again.  

If there are no objections, I'll merge these pull requests and publish 3.3.0.RC4 (I hope this will be the last RC). After that, I'd love to release 3.3.0 within several days if there is no problem.

https://github.com/json4s/json4s/pulls?q=is%3Aopen+milestone%3A3.3+is%3Apr

json4s 4.x will come with new json4s-ast and will contain not a few breaking changes. We should discuss about its plan separately.

- https://github.com/json4s/json4s/issues/266 - JSON4s "2"
- https://github.com/json4s/json4s-ast

If you have ideas or feedbacks, please let me know.

**Comment by seratch** [comment]
As suggested above, I'm going to release 3.3.0.RC4 with fixes as possible as I can.

**Comment by rossabaker** [comment]
:+1: to the plan.

**Comment by mdedetrich** [comment]
+1

**Comment by seratch** [comment]
I just published version 3.3.0.RC4 and started using MiMa with it.

Although there are still bugs and issues [here](https://github.com/json4s/json4s/issues?q=is%3Aopen+), I've worked on existing issues [as possible as I can at this time](https://github.com/json4s/json4s/issues?q=milestone%3A3.3+is%3Aclosed). I'm ready to release 3.3.0 now. If there is no problem, 3.3.0. will be out within a few days.

**Comment by mdedetrich** [comment]
Just letting you know that the first snapshot of json4s-ast was published today, so we have a rough idea of what the AST would look like for Json4s 4.x

**Comment by seratch** [comment]
After fixing issue #299, 3.3.0.RC5 (no code change from RC4) looks fine for me. If there is no problem, I'd like to release 3.3.0 soon.

If you haven't tried the RC version yet, please try it now and let me know if you find something within 24 hours.

**Comment by seratch** [comment]
3.3.0.RC6 was out a week ago. We haven't received any bug reports. I think it's about time to publish 3.3.0.

**Comment by seratch** [comment]
Finally I just published json4s 3.3.0.
