### ISSUE TITLE
json4s 3.3.0.RC4 byte code depends on JDK 8

### ISSUE THREAD

**Issue by seratch** [json4s/json4s#299]
I've built 3.3.0.RC4 on my machine with javac option target/source 1.6 on Oracle JDK 1.8. The build looks invalid as same as that the following article shows...

http://www.draconianoverlord.com/2014/04/01/jdk-compatibility.html

The following Travis builds detected this issue.

- https://travis-ci.org/seratch/skinny-framework/jobs/79986944
- https://travis-ci.org/seratch/skinny-framework/jobs/80078323

```
org.json4s.package$MappingException: java/lang/reflect/Executable Case classes defined in function bodies are not supported.
```

I'll release 3.3.0.RC5 built on JDK 1.7 anyway.

**Comment by xuwei-k** [comment]
FYI https://github.com/sbt/sbt-javaversioncheck

**Comment by seratch** [comment]
Thanks. It looks pretty useful.

**Comment by seratch** [comment]
3.3.0.RC5 is now available.
