### ISSUE TITLE
Split out clean AST model into a dedicated module

### ISSUE THREAD

**Issue by sirthias** [json4s/json4s#3]
Ivan,

we are currently in the process of wrapping up version 2 of spray-json and generally like your approach of trying to establish a common base for Scala JSON implementations.
Ideally, we'd like spray-json to work with a "commonly-accepted" JSON AST model and would be happy to rely on the JSON4S one, if it came with the following features:
1. Dedicated, small and light-weight, no-dependencies artifact.
2. Clean and "pure" AST model without built-in features. This would put all dependent libraries on an equal level and allow them to utilize the full name-space for custom extensions (pimps).
3. Optionally, a simple and clean JSON parser and formatter for basic needs (again, without external dependencies).

The [current AST model](https://github.com/json4s/json4s/blob/master/core/src/main/scala/org/json4s/JsonAST.scala) is probably a good basis but comes with too much functionality already built in for us to feel comfortable to base spray-json on it as is. We'd like it to look a bit more like [the model of our current (unreleased) 2.0 version](https://github.com/spray/spray-json/blob/feature/2.0.0/src/main/scala/spray/json/JsValue.scala). If you'd split it out into a separate module/artifact (e.g. json4s-ast) it'd be even better. 

Would that be something that you'd be interested in?
I think it really would be great if we could help with establishing the JSON4S AST as _the_ reference JSON AST model for Scala...

Cheers,
Mathias

**Comment by magnolia-k** [comment]
Given the current development status of Json4s, can this issue be closed?

**Comment by magnolia-k** [comment]
This issue will be closed as there is no plan to make a major change to Json4s at this time to change the AST.
If someone have any comments, I will reopen.
