### ISSUE TITLE
Json4s fails to serialize scala.Boolean type from a trait

### ISSUE THREAD

**Issue by Sri-Kanth** [json4s/json4s#305]
The scala.boolean type from a trait is not supported and throws a "ScalaSig not found for java.lang.object" error. If the type is converted to "java.lang.Boolean" it works fine. Sample below.

``` scala
import org.json4s._
import org.json4s.native.Serialization
import org.json4s.native.Serialization.{read, write}
import scala.language.dynamics
import scala.beans._

trait SomeTrait {
  @BeanProperty var tbool: Option[String] =  Some("false")

}

class Test extends SomeTrait {
  @BeanProperty var testval: Option[Boolean] =  Some(false)
}

object TestJson4sBool extends App {

  implicit val formats = DefaultFormats + FieldSerializer[Test]() + FieldSerializer[SomeTrait]()

  val k = new Test()  

  println(write(k))

}
```

**Comment by magnolia-k** [comment]
@Sri-Kanth 

Running this code on versions like Json4s 3.3.0 and 3.6.7 did not cause the exceptions described.
Is there any detailed version information? Or can I close this issue if there is no problem at the moment?
