### ISSUE TITLE
build settings for next version

### ISSUE THREAD

**Issue by xuwei-k** [json4s/json4s#306]
3.3.0 final released. I think we should

- [x] create next version branch (3.4 or 4.0 ?)
- [x] change main branch
- disable mima (new branch)
  - [x] modify travis.yml https://github.com/json4s/json4s/blob/1d171687b6dd/.travis.yml#L13
  - [x] set `previousArtifact := None` or remove mima plugin

**Comment by seratch** [comment]
I have done the following things:

- create 3.4 branch and make it the default
- set previousArtifact as None, fix travis.yml
- add CONTRIBUTING.md
- update README on 3.3 to tell users to see the latest

Please let me know if there is any problem related to the above my works. I'm not sure how we should work on 4.0 project yet. It's ok to create 4.0 branch too but I'm afraid multiple active development branches may be a bit confusing. I'll create another issue on this topic.

@casualjim @rossabaker
BTW, I'd love to have @xuwei-k on json4s maintainer team. In fact, he is already [the 3rd contributor](https://github.com/json4s/json4s/graphs/contributors). Can I invite him to the writer team?

**Comment by rossabaker** [comment]
Wow, I thought he already was.  Thanks to @xuwei-k for the contributions, and to whoever was smart enough to add him to the team!
