### ISSUE TITLE
Corner-case problem when extracting case classes inside traits

### ISSUE THREAD

**Issue by afwlehmann** [json4s/json4s#31]
Thanks once again for the 3.2.2 release! I think I might have found a "corner-case" where extracting mixed-in case classes doesn't work:

``` scala
import org.json4s._
import org.json4s.jackson.JsonMethods._
import scala.language.implicitConversions

trait UserModule {
  case class User(id: Option[Int], name: String)
}

object Demo extends App with UserModule {
  implicit val formats = DefaultFormats.withCompanions(classOf[User] -> this)
  val json = """{"name":"joe"}"""
  Console println parse(json).extract[User]
}
```

The problem is the `Option` part. Once you move the declaration of `User` inside the `Demo` object, everything works fine despite the use of `Option`. I had hoped that maybe defining `None` as default value for `id` could serve as a workaround, but that didn't help.

**Comment by magnolia-k** [comment]
At this time (Version 3.6.7), this problem has been resolved and it will complete successfully.
