### ISSUE TITLE
Extract json array of case class to Option[_] using type hints results in key/value map

### ISSUE THREAD

**Issue by haraldmaida** [json4s/json4s#311]
I have a case class Category. Now I want to extract a Seq of Category values from a Json array. This works fine until I do not provide enoug type info to Serialization.read. I thought using type hints should be good enough

here is some code that shows what I'm trying to do:

```
 import org.json4s.native.{ Serialization => ser }
 import org.json4s.DefaultFormats
 import org.json4s.ShortTypeHints

 case class Category(val Code: Int, val DisplayName: String)

object Main extends App {

 implicit val formats = DefaultFormats.withTypeHintFieldName("$type") +
   ShortTypeHints(List(classOf[Category]))

 println(ser.read[Seq[_]]("""[
       {"$type":"Category", "Code":1000000, "DisplayName":"Animals"},
       {"$type":"Category", "Code":52028032, "DisplayName":"Birthday Party"}
     ]"""))

 println(ser.read[Option[Seq[_]]]("""[
       {"$type":"Category", "Code":1000000, "DisplayName":"Animals"},
       {"$type":"Category", "Code":52028032, "DisplayName":"Birthday Party"}
     ]"""))

 println(ser.read[Option[_]]("""[
       {"$type":"Category", "Code":1000000, "DisplayName":"Animals"},
       {"$type":"Category", "Code":52028032, "DisplayName":"Birthday Party"}
     ]"""))
}
```

the result is like this:

```
List(Category(1000000,Animals), Category(52028032,Birthday Party))
Some(List(Category(1000000,Animals), Category(52028032,Birthday Party)))
Some(List(Map($type -> Category, Code -> 1000000, DisplayName -> Animals), Map($type -> Category, Code -> 52028032, DisplayName -> Birthday Party)))
```

First and second result is as expected. But why is the 3rd example  ( ser.read[Option[_] ) producing a List of Map instead of List of Category?
Should'nt the type hints help to find the Category class?
What am I missing?

example from above is also available here http://scastie.org/12663

**Comment by magnolia-k** [comment]
@haraldmaida 

It will be a comment on the old issue, but in the third pattern, the Category is not recognized and the Map that is the default destination of Object is generated?

`Seq[Category]` and `Category` are different and cannot be recognized.
Will it be a solution?

**Comment by haraldmaida** [comment]
Ahhh! I see what you mean. Thanks for the help. Although I'm no longer working on this project, I always enjoy learning. Thanks.
