### ISSUE TITLE
ParserUtil.unquote incorrectly unquotes U+0000 through U+001F.

### ISSUE THREAD

**Issue by sam** [json4s/json4s#333]
See: https://github.com/json4s/json4s/blob/3.4/core/src/main/scala/org/json4s/ParserUtil.scala#L64

`ParserUtil.unquote` makes no accommodation for unicode control-characters.

That means when I parse JSON with the following String:

```javascript
Y31（1987年～） 4ドアハードトップ V30ターボ ブロアムVIP ＜カラードドアミラーはオプション＞\u001d＜新型セドリック・グロリアを発売＞\u001d［VG30ET］［H/T、ハードトップ］［TURBO］ 1987年
```

The `\u001d` will be treated as an encoded unicode character instead of the literal string `\u001d`, meaning it's no longer valid JSON. Now I can't pass it along to other services that properly parse the string since the final result will contain a sequence that can't be represented in a JSON string.

I'm probably butchering the description of the issue, but hopefully that makes sense.

I think the solution would be doing something like changing:

```scala
case 'u' =>
  val chars = Array(buf.next, buf.next, buf.next, buf.next)
  val codePoint = Integer.parseInt(new String(chars), 16)
  s.appendCodePoint(codePoint)
case _ => s.append('\\')
```

To something like:

```scala
case 'u' =>
  val chars = Array(buf.next, buf.next, buf.next, buf.next)
  val codePoint = Integer.parseInt(new String(chars), 16)
  if(codePoint < 32) {
    s.append('\\')
    s.append('u')
    chars foreach(s.append)
  } else {
    s.appendCodePoint(codePoint)
  }
case _ => s.append('\\')
```

**Comment by sam** [comment]
This is a little more complex than I'd hoped. Modifying `unquote` is going to cause round-tripping issues without mirroring the fix in `quote` (which is probably for the best as a correctness issue anyways, but still).

Since `quote` double-escapes back-slash characters, escaped sequences can't be passed within a String or they'll be double-double-escaped. I'm fine with "escaped sequences can't be passed" in the usual case (why would you ever need to do that?), but U+0000 through U+001F has to be treated as special somehow.

**Comment by sam** [comment]
Ok, I've made a mess of this. `\u001d` is a perfectly valid character within a Java String, so I don't think `unquote` needs any modification after all. The issue is that `quote` needs to account for the reserved JSON range of `U+0000` through `U+001F` and it doesn't.

I think. Honestly I've managed to confuse myself pretty thoroughly at this point. All I know is spray-json "does the right thing", and json4s doesn't (yet).

**Comment by sam** [comment]
Taking another stab at it, I think this might fix `quote`:

```scala
if (!AsciiEncoder.canEncode(c))
  if(c < 32) appender.append("\\\\u%04x".format(c: Int))
  else appender.append("\\u%04x".format(c: Int))
else appender.append(c.toString)
```

**Comment by sam** [comment]
Ah. Found it. The test "Escapes control characters" was broken in #179: https://github.com/json4s/json4s/blob/3.4/tests/src/test/scala/org/json4s/native/SerializationBugs.scala#L146

That test shouldn't have changed, because the previous version was actually correct. That range of characters needs to be escaped *in JavaScript String form*. Right now it's testing for the actual codepoints instead: `ser must_== "\"\u0000\u001f\""`.

So this is a regression I guess.

**Comment by mkantor** [comment]
I think #339 fixes this (modulo [your comment about `alwaysEscapeUnicode`](https://github.com/json4s/json4s/pull/339#discussion_r60582054)), right?

**Comment by sam** [comment]
I think so. Thanks!
