### ISSUE TITLE
infinite loop hangs my execution

### ISSUE THREAD

**Issue by hanskoff** [json4s/json4s#351]
Hi,
I have class with optional field and tagged with type
```
case class Person(name: String, age: Int, userId: Option[Long @@ DbUser])
```
where @@ is just an empty marker trait from https://github.com/softwaremill/scala-common#tagging
And the issue is when I try to decompose entities from db I fall into infinite loop without any exception in `ScalaSigReader`:147, second case:
```
 @tailrec def findPrimitive(t: Type): Symbol = t match {
      case TypeRefType(ThisType(_), symbol, _) => symbol
      case ref @ TypeRefType(_, _, _) => findPrimitive(ref)
      case x => fail("Unexpected type info " + x)
    }
```
I see the code has been [changed in current master](https://github.com/json4s/json4s/commit/7fde5fe11add42d271), when do you plan to release it? :)

**Comment by xuwei-k** [comment]
3.4.0 released
