### ISSUE TITLE
question on jackson modules and configuration

### ISSUE THREAD

**Issue by abesanderson** [json4s/json4s#361]
I'm trying to understand the interop support that json4s provides with existing jackson modules and java libraries.   I have some external java libraries which use jackson annotations for de/serialization, as well as some configuration to help deal with various cleanup for the json streams, e.g. DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY.  I have loaded JSR310Module, but neither that nor any of my other configurations seem to be used.  The problem seems to be that all classes deserialized are first decomposed to JValue, and the JValue doesn't handle the java classes very well.  Calling the mapper write function directly with the java object works fine(JsonMethods.mapper.writeValueAsString(foo)), but anything that converts to JValue just gives me an empty JObject.

**Comment by magnolia-k** [comment]
Json4s uses jackson only as a parser, and after parsing, it all works by matching from Json4s AST to Scala objects.

If you want to work with Java collections, you should use Jackson directly
