### ISSUE TITLE
Build and publish a release of json4s-jackson & deps. against current Scala 2.12 milestone

### ISSUE THREAD

**Issue by JoshRosen** [json4s/json4s#362]
It would be great if `json4s` could build and publish `json4s-jackson` artifacts against the current Scala 2.12 milestone (currently 2.12.0-M4). This is a blocker for building Apache Spark against Scala 2.12 (see [SPARK-14439](https://issues.apache.org/jira/browse/SPARK-14439)).

**Comment by xuwei-k** [comment]
http://repo1.maven.org/maven2/org/json4s/json4s-jackson_2.12.0-M4/3.3.0/
