### ISSUE TITLE
type hints should not be extracted on deserialization if there is no matching subclass in hints list

### ISSUE THREAD

**Issue by abesanderson** [json4s/json4s#364]
I have a series of classes that are in an external library that uses a custom field "t" for some of its objects.  However, there are other objects which ALSO use the same field but for values not related to types at all.  For example, {"foo" : {"t":"SubFoo", "data": "stuff"}, "other" : {"a": 123, "b": "123", "t":"just some text"}}.  I'm have a hard time finding a way to keep the type hints from reading that field as a type hint, and because the type hint definition doesn't include that class, it will just generate an empty JObject.  It seems like it should be recognizing that there is not a valid class assignment in the typeHints list and shouldn't even be using the type hinting to resolve how to extract.

**Comment by magnolia-k** [comment]
@abesanderson 

Can this issue be closed because the PR has been merged?

**Comment by abesanderson** [comment]
Yes, fine to close, thanks!
