### ISSUE TITLE
Broken API or Readme

### ISSUE THREAD

**Issue by prettynatty** [json4s/json4s#39]
I have tried to run Validation example from [scalaz/README.md](https://github.com/json4s/json4s/tree/master/scalaz) but on the line

``` Scala
Person.applyJSON(field("name"), validate[Int]("age") >=> min(18) >=> max(60))
```

I get an error:

```
error: type arguments [Int] do not conform to method validate's type parameter bounds [A <: org.json4s.JValue]
              validate[Int]("age")
```

I also found that tests of Validation are marked as pending.

Is there a working way to work with validation now?

**Comment by magnolia-k** [comment]
This issue has been resolved in PR #65.
