### ISSUE TITLE
StreamingJsonWriter#addJValue does not add JLong

### ISSUE THREAD

**Issue by andrewkerr9000** [json4s/json4s#393]
`StreamingJsonWriter#addJValue` does not add `JLong`.

There is a `match` statement in json_writers.scala line 525 matching a `JValue`: `JLong` is not included. Nor is `JNothing`.

The final line (546) of the block is `case _ => this` with will cause any non-matching `JValue`s to be silently ignored, and will prevent the compiler warning of an incomplete `match` even though `JValue` is `sealed`.

A custom serializer serializing a value to `JLong` causes that value to disappear from serialized objects. Using a `JInt` (backed by a Scala `BigInt`) instead appears to fix the problem.

**Comment by ljwagerfield** [comment]
👍
