### ISSUE TITLE
release 3.4.1 (with Scala 2.12.0-RC1)

### ISSUE THREAD

**Issue by xuwei-k** [json4s/json4s#411]
I have pushed some backport (binary compatible) commits from 3.5 to 3.4

https://github.com/json4s/json4s/compare/v3.4.0...3.4

@seratch could you release 3.4.1 (with Scala 2.12.0-RC1) when you have a time? thanks.

**Comment by seratch** [comment]
Done. https://oss.sonatype.org/content/repositories/releases/org/json4s/

3.4.1 for Scala 2.10, 2.11 and 2.12.0-RC1 are available now.

**Comment by xuwei-k** [comment]
Thanks! 😃
