### ISSUE TITLE
parse JSON string error which has Map in Array while using json4s in spark

### ISSUE THREAD

**Issue by gaolei-gl** [json4s/json4s#423]
Hi everyone:
Like the title, I really can't figure out why it fail.....
The json-format string is like this:
```
{
  "lv": "1",
  "u_type": "device",
  "net": "4G",
  "lang": "hi",
  "ts": "1478867402",
  "data": [
    {
      "category": "abc",
      "clicked": 2,
      "ids": [
        "453223423",
        "2347675624"
      ]
    },
    {
      "category": "abc",
      "clicked": 2,
      "ids": [
        "453223423",
        "2347675624"
      ],
    }
  ]
}
```

I try to use those method to extract the data field localy, it successed. But when I launch the job on spark cluster, they all failed. 
```
val actionData = (json \ "data").extract[List[_]]
val actionData = (json \ "data").extract[List[Map[String,_]]]
``` 

error message is like this

    org.json4s.package$MappingException (No information known about type)

I already put implicit val serializerFormats = Serialization.formats(NoTypeHints) in the same scope(with in same method).

BTW: I'm using json4s-native_2.10  version:3.4.0

**Comment by xuwei-k** [comment]
https://github.com/json4s/json4s/issues/316#issuecomment-156816312

**Comment by gaolei-gl** [comment]
@xuwei-k thank you for quick response, I forgot to mention I'm using spark 1.6.2   not 1.5

**Comment by xuwei-k** [comment]
spark 1.6.2 depends on old json4s too. see
http://repo1.maven.org/maven2/org/apache/spark/spark-core_2.10/1.6.2/spark-core_2.10-1.6.2.pom

**Comment by gaolei-gl** [comment]
I need to extract some json which struct like ```Array[Map[String,Any]]   ```
And I notice that we can not extract Map[Stirng,Any] until version 3.2.11.
https://github.com/json4s/json4s/pull/126
