### ISSUE TITLE
Parsing simple String fails.

### ISSUE THREAD

**Issue by jhegedus42** [json4s/json4s#439]
`"bla"` is a valid json (according to http://jsonlint.com/) but json4s cannot parse it.

Described here in detail:
http://stackoverflow.com/questions/41684944/json4s-parsing-fails-for-simple-string-value

Versions:

scalaVersion := "2.11.4"

"org.json4s" %% "json4s-native" % "3.2.11"

Java 1.8.0_91

**Comment by mxl** [comment]
I'm also interested why `parse()` parses only a valid JSON but `render()` can render an invalid JSON.

**Comment by xuwei-k** [comment]
duplicate https://github.com/json4s/json4s/issues/330
