### ISSUE TITLE
Return JArray for Xpath \\

### ISSUE THREAD

**Issue by PSeitz** [json4s/json4s#443]
Was there some conclusion in this discussion: https://github.com/json4s/json4s/commit/a25d169352708b10effdcec5735425b2c8fda636? I would as well prefer JSArray as return type for XPath \\

**Comment by magnolia-k** [comment]
@PSeitz 
It would be a comment on an old issue ...
Is there a better reason for JArray?
It seems that changing the interface from now on will not have much benefit
