### ISSUE TITLE
consider remove "-optimise" scalac option

### ISSUE THREAD

**Issue by xuwei-k** [json4s/json4s#455]
```
[warn] -optimise is deprecated: In 2.12, -optimise enables -opt:l:classpath. Check -opt:help for using the Scala 2.12 optimizer.
```

https://travis-ci.org/json4s/json4s/jobs/216704704#L588

Also `-opt:l:classpath` is danger

http://scala-lang.org/news/2.12.0#new-optimizer

> If you are building a library to publish on Maven Central, you should not inline code from dependencies. Users of your library might have different versions of those dependencies on the classpath, which breaks binary compatibility.

**Comment by eed3si9n** [comment]
Contraband uses an ancient version of json4s, and when Scala 2.12.12 came out it did actually break the binary compatibility. It looks like this trying to use `\(...)` method:

```scala
[error] java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: scala.collection.immutable.List.$anonfun$flatMap$1$adapted(Lscala/runtime/BooleanRef;Lscala/runtime/ObjectRef;Lscala/runtime/ObjectRef;Ljava/lang/Object;)Ljava/lang/Object;
[error] 	at org.json4s.MonadicJValue.findDirectByName(MonadicJValue.scala:25)
[error] 	at org.json4s.MonadicJValue.$bslash(MonadicJValue.scala:18)
```
