### ISSUE TITLE
release for Scala 2.13.0-M1

### ISSUE THREAD

**Issue by xuwei-k** [json4s/json4s#459]
### dependency libraries
- [ ] specs2 (testing only. we can release without test)

**Comment by xuwei-k** [comment]
I will release 3.5.2
https://issues.sonatype.org/browse/OSSRH-13198

**Comment by xuwei-k** [comment]
https://oss.sonatype.org/content/repositories/releases/org/json4s/json4s-core_2.13.0-M1/

**Comment by seratch** [comment]
Sorry for missing this. Thanks a lot.
