### ISSUE TITLE
Using Scala 2.10.1 with json4j causing unexpected behavior

### ISSUE THREAD

**Issue by chesterxgchen** [json4s/json4s#46]
I am not sure this is bug/issue, but would like to report this behavior. 

In my project, I specified scala version to be 2.10.1

During compilation,  I got the following message

Potentially incompatible versions of dependencies of {file:/...} ...:
[warn]    org.scala-lang: 2.10.1, 2.10.0

search on the web found that the sbt choose to set suppress warning except for debug

conflictWarning in ThisBuild ~= { _.copy(level = Level.Debug) }

this suppress the warning. But regardless the warning suppressed or not , when you the test: you will have the following, my test (testNG)

  import jackson.Serialization.{read, write => swrite}
  implicit val formats = jackson.Serialization.formats(NoTypeHints)

  case class Project(name: String, startDate: Date, lang: Option[Language], teams: List[Team])
  case class Language(name: String, version: Double)
  case class Team(role: String, members: List[Employee])
  case class Employee(name: String, experience: Int)
  case class Nullable(name: String)

  val project = Project("test", new Date, Some(Language("Scala", 2.75)), List(
    Team("QA", List(Employee("John Doe", 5), Employee("Mike", 3))),
    Team("Impl", List(Employee("Mark", 4), Employee("Mary", 5), Employee("Nick Noob", 1)))))

  @Test
  def testSerialization() {
    val ser = swrite(project)
    val project1  = read[Project](ser)
    assert( project1.name == project.name )  // ok
    assert( project1.lang.get.name == project.lang.get.name )  // ok
    assert( project1.lang.get.version == project.lang.get.version ) // ok
    assert( project1.lang.get == project.lang.get )  //failed
    assert( read[Project](ser).equals(project) ) //never reach here. 
  }

but the following tests are fine

 @Test
  def testEquals() {
   val project1 = project.copy()
    assert(project1 == project) //ok
   assert( Some(Language("Scala", 2.75)) ==  Some(Language("Scala", 2.75)) ) //ok
  }

Once I switch the scala version to 2.10.0, 

all above tests passed.

**Comment by seratch** [comment]
Thanks to @xuwei-k, json4s 3.3 has its own scalap fork which is stable while upgrading scala-lang minor versions. I think we can close this issue now.
