### ISSUE TITLE
Parsing Mutable Maps

### ISSUE THREAD

**Issue by jeetukiran** [json4s/json4s#466]
### jdk version: 1.8.0_131

Is extracting to a Mutable Map supported? When I try to run the code below I get an error 

`java.lang.ClassCastException: scala.collection.immutable.Map$Map1 cannot be cast to scala.collection.mutable.Map`

```
import org.json4s.jackson.JsonMethods._
import scala.collection.mutable

object JsonDeserializerTesting {
  implicit val formats = org.json4s.DefaultFormats

  def main(args: Array[String]): Unit = {
    val mapJson = """{"name":"Art Institute", "address": {"city":"Chicago"}}"""
    val parsedMap = parse(mapJson)
    val extractedMap = (parsedMap \ "address").extract[mutable.Map[String, AnyRef]]
    println(extractedMap.getClass)
  }

}
```

Parsing to a mutable.Seq works, the test case in project seems to be parsing to an immutable.Map.

https://github.com/karthicks/json4s/blob/c57d71062f852ab50b786fb5f888623b5b8e1c8b/tests/src/test/scala/org/json4s/ExtractionExamplesSpec.scala#L72

Thanks,
Jeetu

**Comment by xuwei-k** [comment]
3.5.3 released
