### ISSUE TITLE
ScalaJSON AST first milestone release on scala-platform

### ISSUE THREAD

**Issue by mdedetrich** [json4s/json4s#468]
Finally, after the SLIP-28/scala-contributors submission is over, ScalaJSON ast is now part of the Scala platform (and the ScalaJSON AST is now released as its first milestone `1.0.0-M1`, you can see more of the details here https://github.com/mdedetrich/scalajson). This is also a period of time where any last minute changes can be proposed.

This issue is in regards to json4s integrating ScalaJSON AST (this was actually one of the original goals of the ScalaJSON AST, which was started by one of the original contributors of Json4s, @casualjim )

The change shouldn't be expected to be too difficult, albeit there are differences with some of the datastructures (i.e. using `Map` for `JObject` and `Vector` for `JArray` instead of `List` and `List`), however apart from this there shouldn't be any big differences.

This is also the first step for Scala.js support (since the AST already supports Scala.js) although you would have to remove the reflection in json4s.

**Comment by magnolia-k** [comment]
There doesn't seem to be much of a need to make major changes to Json4s now for interconversion with other JSON libraries.

I'm closing this issue, but if further discussion is needed, please reopen it.
