### ISSUE TITLE
Json4s not serializing non-case classes even FieldSerializer

### ISSUE THREAD

**Issue by gursahibexp** [json4s/json4s#469]
### jdk version - 8

I am trying to return a non-case class object as a JSON to a POST endpoint. I am using the FieldSerializer assuming it would parse the non-case to a JSON and return the response.

Code snippet : ` protected implicit lazy val jsonFormats: Formats = DefaultFormats + FieldSerializer[ResponseStatus]() +FieldSerializer[SubmitClaimResponse]()
 `
But it doesn't work that way 

Why am not using case classes because these classes are imported as a contract in my scalatra API codebase. jsonschemtopojo converts the json schema to respective non-case classes

**Comment by magnolia-k** [comment]
@gursahibexp 

Sorry for the very late response, but is there still interest in this issue?

It seems that if we had more information we could analyze it, but we don't have enough information.

I'm going to close this issue, but if you need to, show me reproducible code and I'll reopen it.
