### ISSUE TITLE
release 3.2.11 for Scala 2.12 for apache spark

### ISSUE THREAD

**Issue by xuwei-k** [json4s/json4s#472]
https://github.com/apache/spark/pull/18645

**Comment by xuwei-k** [comment]
current [3.2 branch](https://github.com/json4s/json4s/commits/519af490a98105d9e5a9cd3f51dd43d35f1d8c5a) is only for Scala 2.9.

I want to 
- rename `3.2` branch => `3.2_Scala2.9`
- restore `3.2` from [`v3.2.0_2.10` tag](https://github.com/json4s/json4s/tree/v3.2.10_2.11) (it means need `git push -f`). and then I will drop some modules(scalaz, mongo, etc), drop Scala 2.10 build, add Scala 2.12 build, add [mima](https://github.com/typesafehub/migration-manager). [Here is WIP commit](https://github.com/xuwei-k/json4s/commit/64b410045d9118e41c95e8c871d24394339c7508)

@seratch WDYT? If you agree to this, could you give me the admin authority? because `3.2` is protected branch. or should we keep current 3.2 branch and create new branch? (e.g. `3.2_scala2.12` )

**Comment by seratch** [comment]
I would like to express my gratitude to you for your efforts on it. I've changed your role to an Owner. Considering your contributions to the project, I believe nobody opposes it.

**Comment by xuwei-k** [comment]
- https://oss.sonatype.org/content/repositories/releases/org/json4s/json4s-jackson_2.12/3.2.11
- https://github.com/json4s/json4s/releases/tag/v3.2.11_2.12
