### ISSUE TITLE
Spark and Json4s 3.2.10, 3.2.11 issues and solutions.

### ISSUE THREAD

**Issue by acmitch** [json4s/json4s#473]
**Note: It would be great if the following were resolved in both 3.2.10 and 3.2.11 to eliminate the need of manual effort to fully utilize this fantastic library on the Spark cluster.**

Json4s can be a major headache when utilizing with Spark. Especially, when using Spark 1.6 which is currently in use by most big data platforms (Cloudera & Hortonworks).

For anyone having issues with Spark, understand that Spark Core utilizes Json4s and because major modifications within minor versions of Json4s I have found no easy way to solve the problems without cloning and cherry picking commits into the specific version Spark utilizes.

Spark 1.6 -> Json4s 3.2.10
Spark 2.0 -> Json4s 3.2.11

**Issues:**
    #126 - In my opinion, this makes Json4s 3.2.10 unusable in Spark 1.6 if needing to deserialize data. (This is fixed in 3.2.11 if using Spark 2.0)
    #162 - Json4s TypeHints do not work in versions 3.2.10 and 3.2.11 when using with Spark 1.6 or 2.0 on a cluster. I don't fully understand the problem, but my initial guess is that somehow due to Spark serialization Json4s fails to resolve the class from the classloaders.

**Solutions:** 
    To fix both issues clone Json4s 3.2.10 or 3.2.11, depending on your version of Spark, and make changes outlined within the commits, then edit the SBT file to package/publish a new hotfix version of the core (3.2.10.1). Utilize this version in your projects. Since the changes exist in the Json4s Core you can easily utilize the 3.2.10.1 jar by prepending on the Spark classpath. Keep in mind if utilizing on the cluster you will need to override on the executor classpaths as well via the spark.executor.extraClassPath and provide to the --jars param on spark-submit.

**Recommended changes:**
#193 - I also recommend fixing the deprecation issues outlined in this commit. Not sure if this actually helps, but we made these changes during the debugging process to eliminate any weirdness.

Related Discussions:
#316
#418
#212

**Comment by magnolia-k** [comment]
@acmitch 

It's a very slow response, is this issue still need discussion?
Both Spark and Json4s have advanced versions and the solution seems to be changing.

**Comment by acmitch** [comment]
@magnolia-k this can be closed. I raised before Spark 2.0 was supported by Hadoop providers. Spark 2.0 fixes the main concerns.
