### ISSUE TITLE
Could not use Xpath to get value

### ISSUE THREAD

**Issue by BrickXu** [json4s/json4s#476]
### json4s version
libraryDependencies += "org.json4s" % "json4s-jackson_2.10" % "3.4.2"
libraryDependencies += "org.json4s" % "json4s-native_2.10" % "3.4.2"
### scala version
2.10.4
### jdk version
jdk8u60

I use the example in the readme docs and it does not work as excepted.

```
import org.json4s._
import org.json4s.native.JsonMethods._

val test = parse(""" { "message" : "hello!" } """)
println(test.getClass)
println(test \\ "message")
```

it throws an exception with a different class type, what's wrong with it ?

```
class org.json4s.JsonAST$JObject
Exception in thread "main" java.lang.NoSuchMethodError: scala.collection.immutable.$colon$colon.hd$1()Ljava/lang/Object;
```

it makes me so confused a few days.

**Comment by xuwei-k** [comment]
I assume you have multiple binary incompatible json4s or scala-library jars in your classpath.

**Comment by magnolia-k** [comment]
@BrickXu 
Is the problem solved?
Can this issue be closed?

**Comment by BrickXu** [comment]
@magnolia-k we use jackson instead of this pkg, this issue can be closed.
