### ISSUE TITLE
Java8 Date & Time API support

### ISSUE THREAD

**Issue by takezoe** [json4s/json4s#477]
Is there any chance to add Java8 Date & Time API support as same as Joda-Time support in ext module?

I found old issue (#271) and pull request (#243), but the pull request was rejected to keep binary compatibility. How about adopting it in the current development branch? or as an another module?

**Comment by xuwei-k** [comment]
> How about adopting it in the current development branch? 

👍  for 3.6 branch. It's time to drop Java 7 support.

**Comment by takezoe** [comment]
Thanks. I'll create a new pull request.
