### ISSUE TITLE
ext package - two EnumNameSerializers can't be added to formats

### ISSUE THREAD

**Issue by TimPigden** [json4s/json4s#5]
In the ext package if I have 2 EnumNameSeraiizer objects, in my Formats then it looks as though the extractor is only looking at one of them and gives me a "No usable value for .." 
Can't convert JString(Employee) to class scala.Enumeration$Value) 

If I reverse the order in which I add them to formats it works. So it looks as though it fails on the first Enumeration it encounters and doesn't proceed through the list.

Could that be possible?

**Comment by magnolia-k** [comment]
This issue is considered closeable, as the following PRs have been merged.

https://github.com/json4s/json4s/pull/511

**Comment by magnolia-k** [comment]
This issue will be resolved in the following PR, so I will close it.

https://github.com/json4s/json4s/pull/511

If someone has another problem, open another issue
