### ISSUE TITLE
Drop native import from TypeFieldSerializer

### ISSUE THREAD

**Issue by zcourts** [json4s/json4s#509]
### json4s version
3.6.0-M2
### scala version
2.12.4
### jdk version
1.8.u160

https://github.com/json4s/json4s/blob/043235c40d21b7f00d6e00f6b169a648ae13e79e/ext/src/main/scala/org/json4s/ext/TypeFieldSerializer.scala#L10
Imports the native module, if you're using e.g. Jackson instead then `TypeFieldSerializer` will fail at runtime due to `NoClassDefError`.

**Comment by magnolia-k** [comment]
@ncolomer 

The code added in the following PR is not compatible with jackson. Do you have any ideas on how to fix it?

https://github.com/json4s/json4s/commit/043235c40d21b7f00d6e00f6b169a648ae13e79e

**Comment by xuwei-k** [comment]
https://github.com/json4s/json4s/commit/caf879332965069b7e69f1cec24a86d6e19d7e77
