### ISSUE TITLE
Empty nested JObjects are not omitted on rendering

### ISSUE THREAD

**Issue by lmdehaas** [json4s/json4s#526]
### json4s version
3.5.3

### scala version
2.12.4

### jdk version
1.8.0

Given this code, where both `name` and `id` are Options returning None:
```
val json = 
  ("key1" -> "value") ~
  ("key2" -> ("name" -> name) ~ ("id" -> id))

compact(render(json))
```
I would expect it to evaluate to `{"key1": "value"}`. Instead, it evaluates to
```
{
  "key1": "value",
  "key2": {}
}
```

To return the result I want, I need to check all fields:
```
val json = 
  ("key1" -> "value") ~
  ("key2" -> (if (name.isDefined | id.isDefined) ("name" -> name) ~ ("id" -> id) else JNothing))

compact(render(json))
```

I would expect omitting empty nested JObjects to be default behavior in json4s. Is this a bug or a feature?

**Comment by fr101ed** [comment]
I have a similar question. How to check a JValue is an empty json. For example

```
val json = parse("""{}""")
```

I would expect there is a method like `isEmpty`:
```
json.isEmpty == true // which is true
```

**Comment by YikSanChan** [comment]
@fr101ed You can simply check `json.children.isEmpty`

**Comment by magnolia-k** [comment]
@lmdehaas 

The solution is shown.
May this issue be closed?
