### ISSUE TITLE
java.lang.NoClassDefFoundError: org/json4s/jackson/JsonMethods$

### ISSUE THREAD

**Issue by ruanwenjun** [json4s/json4s#535]
### json4s version
3.5.1
### scala version
2.11.8
### jdk version
1.8

I try to parse  a String to json

val response = parse(res, useBigDecimalForDouble = true)

then , it throw the exception

**Comment by xuwei-k** [comment]
Can't reproduce. Please provide more informations (e.g. your `build.sbt`)

**Comment by ruanwenjun** [comment]
@xuwei-k Thank you for your response, when i use the Json4s Jackson , the problem has been solved , the build.sbt  below

name := "Hello"
version := "1.0"
scalaVersion := "2.11.8"

val spark_gid = "org.apache.spark"
val spark_version = "2.1.1"
val excludeServletApi = ExclusionRule(organization = "javax.servlet")
val excludeEclipseJetty = ExclusionRule(organization = "org.eclipse.jetty")
val excludeJetty = ExclusionRule(organization = "org.mortbay.jetty")
javacOptions ++= Seq("-encoding", "UTF-8")


assemblyMergeStrategy in assembly := {
  case "application.conf" => MergeStrategy.concat
  case "org/apache/spark/unused/UnusedStubClass.class" => MergeStrategy.discard
  case "META-INF/MANIFEST.MF" => MergeStrategy.discard
  case PathList("META-INF", "MANIFEST.MF") => MergeStrategy.discard
  case f if f.matches("META-INF.*\\.(SF|DSA|RSA)$") => MergeStrategy.discard
  case x =>
    //val oldStrategy = (assemblyMergeStrategy in assembly).value
    //oldStrategy(x)
    MergeStrategy.last
}

assemblyShadeRules in assembly := Seq(
  ShadeRule.rename("com.google.protobuf.*" -> "shadedproto.@1").inProject
    .inLibrary("com.google.protobuf" % "protobuf-java" % "3.5.1")
)

resolvers ++= Seq(
  "Sonatype Snapshots" at "http://oss.sonatype.org/content/repositories/snapshots",
  "Sonatype Releases" at "http://oss.sonatype.org/content/repositories/releases",
  "Sonatype OSS Snapshots Repository" at "http://oss.sonatype.org/content/groups/public",
  "Apache" at "http://maven.apache.org",
  "gphat" at "https://raw.github.com/gphat/mvn-repo/master/releases/",
  "Redis Maven" at "https://dl.bintray.com/spark-packages/maven",
  "Alibaba" at "https://mvnrepository.com/artifact/com.alibaba",
  "Sohu public" at "http://10.11.159.110:8082/nexus/content/groups/sohu-public/",
  "Sohu central" at "http://10.11.159.110:8082/nexus/content/repositories/central/",
  "Sohu apache" at "http://10.11.159.110:8082/nexus/content/repositories/apache-release/",
  "Sohu private" at "http://nexus.dis.sohucs.com/content/groups/public/"
)


libraryDependencies ++= Seq(
  //*********** spark ****************
  spark_gid %% "spark-core" % spark_version % "provided",
  spark_gid %% "spark-mllib" % spark_version % "provided",
  spark_gid %% "spark-streaming" % spark_version % "provided",
  spark_gid %% "spark-streaming-kafka-0-10" % spark_version,
  //spark_gid %% "spark-sql" % "provided",
  "com.github.nscala-time" %% "nscala-time" % "2.16.0",
  "com.typesafe" % "config" % "1.3.1",
  //"redis.clients" % "jedis" % "2.9.0",
  "redis.clients" % "sce-jedis" % "2.9.0", 
  "org.apache.commons" % "commons-pool2" % "2.4.2",
  "org.jsoup" % "jsoup" % "1.10.2",
  "org.json4s" %% "json4s-native" % "3.5.1",
  //*********** hbase ****************
  "org.apache.hbase" % "hbase-client" % "0.98.16.1-hadoop2",
  "org.apache.hbase" % "hbase-common" % "0.98.16.1-hadoop2",
  "org.apache.hbase" % "hbase-server" % "0.98.16.1-hadoop2" excludeAll(excludeJetty, excludeServletApi, excludeEclipseJetty),
  "org.jblas" % "jblas" % "1.2.4",
  "com.github.scopt" % "scopt_2.11" % "3.2.0",
  "org.clapper" % "grizzled-slf4j_2.11" % "1.3.1",
  "org.apache.commons" % "commons-lang3" % "3.6",
  "com.twitter" %% "util-collection" % "6.23.0",
  "mysql" % "mysql-connector-java" % "5.1.34",
  "com.alibaba" % "fastjson" % "1.2.38",
  "com.hankcs" % "hanlp" % "portable-1.3.4",
  "org.mongodb.spark" % "mongo-spark-connector_2.11" % "1.1.0",
  "io.spray" % "spray-json_2.11" % "1.3.3",
  "com.google.protobuf" % "protobuf-java" % "3.5.1",
  "org.scala-lang" % "scala-reflect" % "2.11.8",
  "commons-dbcp" % "commons-dbcp" % "1.2.2",
  "io.reactivex.rxjava2" % "rxjava" % "2.1.11", 
  "org.apache.commons" % "commons-collections4" % "4.1",
  "org.tensorflow" % "tensorflow" % "1.7.0",
  "com.google.code.gson" % "gson" % "2.8.0",
  "com.hadoop.gplcompression" % "hadoop-lzo" % "cdh4-0.4.15-gplextras",
  "com.ctrip.framework.apollo" % "apollo-client" % "0.11.0-panther"

)

**Comment by xuwei-k** [comment]
Spark depends on old version json4s. You should use old json4s or another json library.
