### ISSUE TITLE
underscoreKeys transform camel case as well kebab case 

### ISSUE THREAD

**Issue by btomala** [json4s/json4s#545]
### json4s version
2.5.3
### scala version
2.12.6
### jdk version
1.8.0_181

UnderscoreKeys which is also snakizeKeys It's working well until I want to transform class which have fields written with camel case and map where the key is UUID.

Sample code
```scala
case class Keys(myMap: Map[UUID,Int])
val k = Keys(Map(UUID.random(), 1))
compact(render(Extraction.decompose(k)))  //{"myMap":{"565b2803-fdb9-4359-8c39-da1a347d76ca": 1}}
compact(render(Extraction.decompose(k).underscoreKeys))  //{"my_map":{"565b2803_fdb9_4359_8c39_da1a347d76ca": 1}}
```

I suggest to split the implementation of the `underscoreKeys` in two functions (underscoreCamelKeys/underscoreKebabKeys) and expose them as a part of the API. For the backward compatibility, the old `underscoreKeys` could be a composition of those two.

**Comment by seratch** [comment]
Fixed by PR #556
