### ISSUE TITLE
ScalaSig exception on FieldSerializer with TypeTag

### ISSUE THREAD

**Issue by yadavan88** [json4s/json4s#548]
### json4s version
3.6.1
### scala version
2.12.6
### jdk version
1.8

I am using FieldSerializer for serializing non-case class fields to json. It is working fine in simple scenario. But if I add TypeTag to the mix, then I am getting `Can't find ScalaSig for class java.lang.ClassLoader` error. 

I have pasted the sample code in git gist [here](https://gist.github.com/yadavan88/94fd289365549b5a6c37cbabae8c162e).

This same scenario was working with `scala 2.11` and `json4s 3.4` before. Facing this issue, when I tried to upgrade our application to `scala 2.12`.

**Comment by adriaanm** [comment]
My guess is that the serializer is running into the field of type `TypeTag[Employee]` (synthesized for the context bound on `T` in `Copyable`). A TypeTag transitively points to a class loader (through the mirror field).

**Comment by yadavan88** [comment]
@adriaanm  Thanks for the response. We have to keep the type tag. Is there any workaround that I can try?

**Comment by yadavan88** [comment]
Any help on this please ? My scala 2.12 upgrade is stuck due to this issue.

**Comment by adriaanm** [comment]
I don't think there's a way to serialize type tags to json. I guess you could add a dummy serializer for type tags? By adding it as a context bound to a class type parameter `T`, you introduce a field of type `TypeTag[T]`. So, you could try pushing it down to a method type param. I don't know much about json4s, so I can't really provide more detailed suggestions.

**Comment by yadavan88** [comment]
@adriaanm Thank you very much, for taking your time to reply. I will try as you mentioned.

**Comment by magnolia-k** [comment]
Has this issue been resolved in the way you suggested?
I will close the issue, but please reopen it if you have another problem
