### ISSUE TITLE
Flattening causes strings to be doubly quoted

### ISSUE THREAD

**Issue by Wosin** [json4s/json4s#551]
### json4s version
3.6.1
### scala version
2.11.11
### jdk version
8

Hello, 
Is there any specific reason why `Extraction.flatten()` adds additional quotes to the flattened value if it is `JString()` ?? Currently, flattening JSON with string fields will result in something like below:
{"key":"value"}
ends up as map
`".key"-> ""value""`

Thanks for the response.

**Comment by Wosin** [comment]
Hey, 
Any update on this ?
Best Regards,
Dom.

**Comment by seratch** [comment]
IFAIK, there should be no reason.

**Comment by Wosin** [comment]
Ok, so I assume its a bug here. 
I will try to make a fix for that.

**Comment by Wosin** [comment]
Okay, I think I had some issue, but it really seems that there is only single quoting in the map, but I guess it is necessary to be able to unflatten the String properly, so this issue should be closed.
