### ISSUE TITLE
Why JInt takes BigInt while JLong takes Long?

### ISSUE THREAD

**Issue by YikSanChan** [json4s/json4s#559]
### json4s version
Not related.

### scala version
Not related.

### jdk version
Not related.

Hi folks, I am wondering why `JInt(num: BigInt)` while `JLong(Long)`? Which actually means `JInt` has larger range than `JLong`, which can be confusing as people usually assume int has smaller range than long and it should.

**Comment by magnolia-k** [comment]
@YikSanChan 

Originally there was only JInt, JLong was added later.

https://github.com/json4s/json4s/pull/253

There is no restriction on the number of JSON, so I think using BigInt is appropriate.

**Comment by magnolia-k** [comment]
@YikSanChan 
solved the problem? 
Can this issue be closed?
