### ISSUE TITLE
Preserving empty values strategy doesn't work for Seq[Option[T]]

### ISSUE THREAD

**Issue by izayarniy** [json4s/json4s#561]
### jdk version 1.7
It seems that preserving empty values strategy doesn't work.
```
    val values = Seq(Some(1),None, None)
    implicit val formats: Formats = DefaultFormats.preservingEmptyValues
    val stringWriter = new StringWriter()
    Serialization.write(values, stringWriter)(formats)
    println(stringWriter.toString)
```
Expected output [1, null, null]
Current output   [1]

**Comment by Ouriel** [comment]
Hi,
Just stumble upon the same issue.
`
> implicit val formats: Formats = DefaultFormats.preservingEmptyValues
> val test =read[List[Option[Long]]]("[12,12,null]")
test: List[Option[Long]] = List(Some(12), Some(12), None)
> write(test)
res1: String = [12,12]
`

Is there any update on this issue?

Thanks

**Comment by dalegaspi** [comment]
you can provide your own `EmptyValueStrategy` to `DefaultFormats` to change the behavior.

```scala
DefaultFormats.withEmptyValueStrategy(new EmptyValueStrategy {
    def noneValReplacement = None

   // this is a sample...replace with your own strategy

    def replaceEmpty(value: JValue): JValue = value match {
      case JArray(items) => JNothing
      case JObject(fields) => JObject(fields map {
        // you may have to do an Option check here?
        case JField(name, value) => JField(name, replaceEmpty(value))
      })
      case JNothing => JNothing
      case oth => oth
    }
  }
)
```

**Comment by magnolia-k** [comment]
preservingEmptyValues doesn't support Option.

**Comment by magnolia-k** [comment]
@izayarniy 

solved the problem?
Can an issue be closed?
