### ISSUE TITLE
seq2jvalue method replaced Traversable with Iterable parameter type, breaking Spark

### ISSUE THREAD

**Issue by mellster2012** [json4s/json4s#568]
### json4s version
3.6.2
### scala version
2.12
### jdk version
1.8
### spark version
2.4.0

In 3.6.2
  implicit def seq2jvalue[A](s: Iterable[A])(implicit ev: A => JValue) = ...
causing:
java.lang.NoSuchMethodError: org.json4s.JsonDSL$.seq2jvalue(Lscala/collection/Traversable;Lscala/Function1;)Lorg/json4s/JsonAST$JArray; at org.apache.spark.sql.types.StructType.$anonfun$jsonValue$3(StructType.scala:333)

In 3.5.4
  implicit def seq2jvalue[A](s: Traversable[A])(implicit ev: A => JValue) = ...
works.

Is it possible to add the seq2jvalue with the Traversable parameter type back to the implicit conversions in addition to seq2jvalue with the Iterable parameter type?

**Comment by xuwei-k** [comment]
Please use json4s 3.5.x if use spark.

**Comment by thiagomata** [comment]
I am having this same issue with spark 3.0.2 scala 2.12.10. Changing the json4s to the 3.5.3 did not help.
