### ISSUE TITLE
Make target case an option in Formats

### ISSUE THREAD

**Issue by jond3k** [json4s/json4s#58]
Many APIs use snake case in field names but it's canonical to use camel case in Scala.

There's a way to interoperate by using the snakeize method on serialization and camelize on deserialization in json4s but the process is convoluted. 

To interoperate seamlessly, we could add a new parameter to the formats trait, e.g.

```
implicit val json4sFormats = new DefaultFormats {
  override val snakeCaseSerialization = true
}
```

Alternatively:

```
implicit val json4sFormats = new DefaultFormats {
  override val serializationCase = SnakeCase
}
```

**Comment by ezoerner** [comment]
+1

**Comment by btomala** [comment]
Hi guys what do you think about https://github.com/btomala/json4s/pull/1 solution?
Unfortunately this brake binary compatibility. If you want to include this solution to your distribution I can rise PR to your repository. I don't have big knowledge about json4s. I choose this story to get to know something about internals of it.  I'm also open for advice and collaborating on this task. I also didn't run any performance test.

**Comment by magnolia-k** [comment]
@btomala 
Sorry for the very late reply, but this PR can't be merged right now, but can you solve it?

**Comment by btomala** [comment]
I'll try to do this next week
