### ISSUE TITLE
json4s get wrong result when resolve SimpleDateFormat

### ISSUE THREAD

**Issue by Jassy1994** [json4s/json4s#589]
### json4s version
3.2.11

### scala version
2.11.8

### jdk version
1.8

I get wrong result in resolve Object contains SimpleDateFormat，This is my code：
```
implicit val formats = DefaultFormats
val res = Extraction.decompose(ArrayBuffer("xxxx", new SimpleDateFormat("2018-02-12")))
println(res)
```
and print result is：get a void JObject but not JString.
```
JArray(List(JString(xxxx), JObject(List())))
```

Any Idea for resolving date format like "2018-02-12"?
thanks a lot.

**Comment by magnolia-k** [comment]
@Jassy1994 

Since SimpleDateFormat is a class representing date format, is it not suitable for direct conversion to Json?
If you want to output the contents of the format, is it appropriate to call SimpleDateFormat.toPattern?

**Comment by Jassy1994** [comment]
@magnolia-k 
Thanks for your comment, I will make a test and report the result. in a simple test, this solution did solve this problem.

**Comment by magnolia-k** [comment]
@Jassy1994 
solved the problem? 
Can this issue be closed?
