### ISSUE TITLE
Option to NOT serialize empty Seq[]

### ISSUE THREAD

**Issue by dalegaspi** [json4s/json4s#591]
i have this case class:

```scala

case Episode(name: String)
case class Channel(name: String = "hello", episodes: scala.Seq[Episode] = Nil)
```

it seems that the default behavior is to serialize empty arrays (using Jackson serialization here)...like this is the result for a default instance for `Channel`:

```json
{
  "name": "hello",
  "episodes": []
}
```

and i want this instead:

```json
{
  "name": "hello"
}
```

how do I configure json4s to not serialize empty arrays?

i tried to add these lines in my app (from README) and neither seemed to work for me:

```scala org.json4s.jackson.JsonMethods.mapper.setSerializationInclusion(JsonInclude.Include.NON_EMPTY)
org.json4s.jackson.JsonMethods.mapper.configure(SerializationFeature.WRITE_EMPTY_JSON_ARRAYS, false)
```

I also played with the `DefaultFormatswithEmptyValueStrategy(EmptyValueStrategy.skip)` (which is the default anyway when i peeked into json4s code) and the empty Seq is still being rendered.

pls advise.  thanks!

### json4s version
3.5.2
### scala version
2.12
### jdk version
8

**Comment by magnolia-k** [comment]
@dalegaspi 

'SerializationFeature.WRITE_EMPTY_JSON_ARRAYS' is for Array.

Are the following articles helpful?

https://stackoverflow.com/questions/15426232/dont-return-property-when-its-an-empty-list-with-jackson

**Comment by nklnandu** [comment]
I have tried the below , it works for me. 

  object NullOrEmptyFieldSerializer extends CustomSerializer[Any]( format => (
    {
      case JString(any: Any) => any
    },
    {
      case "" => JNothing
      case null => JNothing
      case Seq() => JNothing
    }))

**Comment by 00bharat7** [comment]
Thanks @nklnandu , this works
