### ISSUE TITLE
How to get the last value for duplicated fields

### ISSUE THREAD

**Issue by visualskyrim** [json4s/json4s#592]
### json4s version
json4s-jackson 3.6.5
### scala version
2.11.12
### jdk version
1.8.0_161

The json4j turns values from duplicated fields into an array.
For example:
```
{
  "a": "1",
  "a": "2"
}
```

will become
```
json \ "a"
> JArray(List(JString(1), JString(2)))
```

Is there a way to only get the last value of the array for this field?

**Comment by magnolia-k** [comment]
There is no way to combine duplicate keys into one at the AST stage.

Convert to Map, the last key will be valid.

```scala
scala> val j = parse("""{"a": "1", "a": "2"}""")
j: org.json4s.JValue = JObject(List((a,JString(1)), (a,JString(2))))

scala> val m = j.extract[Map[String, String]]
m: Map[String,String] = Map(a -> 2)
```

**Comment by magnolia-k** [comment]
@visualskyrim 

solved the problem?
Can this issue be closed?
