### ISSUE TITLE
Timezone is forced to UTC even when overriding date format

### ISSUE THREAD

**Issue by ShardPhoenix** [json4s/json4s#60]
As suggested in the Readme, it is possible to provide a custom date format like follows:

``` Scala
implicit val formats = new DefaultFormats {
         override def dateFormatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
       }
```

However, even if this custom date format has a non-UTC timezone, it will be set to UTC anyway. This happens in the "formatter" private method in DefaultFormats (inside Formats.scala):

``` Scala
    private[this] def formatter = {
        val f = df()
        f.setTimeZone(DefaultFormats.UTC)
        f
      }
```

I'd suggest that the line "f.setTimeZone(DefaultFormats.UTC)" should be moved from "formatter" to the "dateFormatter" method below. That way, using a custom date with a custom timezone will work correctly. In the meantime, there is a workaround by implementing DateFormat (using a custom "datePattern" and "timeZone"):

``` Scala
  implicit val formats = new Formats {

    val dateFormat = new DateFormat {
      def parse(s: String) = try {
        Some(formatter.parse(s))
      } catch {
        case e: ParseException => None
      }

      def format(d: Date) = formatter.format(d)

      private def formatter = {
        val dateFormat = new SimpleDateFormat(datePattern)
        dateFormat.setTimeZone(TimeZone.getTimeZone(timeZone))
        dateFormat
      }
    }
  }
```

**Comment by magnolia-k** [comment]
This issue has already been resolved.
