### ISSUE TITLE
Invalid JSON is parsed with no error

### ISSUE THREAD

**Issue by atsyganenko** [json4s/json4s#613]
### json4s version
3.6.7
### scala version
2.12
### jdk version
1.8

rg.json4s.native.JsonMethods are used

1. column follows empty json 
JsonMethods.parse("{} :") returns JObject(List()) with no error
2. missed comma 
JsonMethods.parse("""{"data":"some_data" "value":"some_value"}""") returns JObject(List((data,JString(some_data)), (value,JString(some_value))))
 with no error

**Comment by plokhotnyuk** [comment]
@atsyganenko As W/A you can use a parser from the latest version of the jsoniter-scala-core library which aim to fulfill all requirements of the JSON specification. While it doesn't provide an integration with json4s AST it can be easily implemented for your needs, including efficiency or [resistance to DoS attacks](https://github.com/json4s/json4s/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+denial+of+service). Please see [an example of a custom codec for dijon AST](https://github.com/pathikrit/dijon/blob/827ce7a1a6041594f6bb28c9306553eb44d1c136/src/main/scala/com/github/pathikrit/dijon/package.scala#L103-L161)

**Comment by weiss-gal** [comment]
I found a similar problem when parsing invalid JSON:
parse("[[]") returns JNothing
Although I would expect this case to yield an exception as any other invalid JSON

json4s version: 3.5.3 (using native backend)
scala version: 2.11
jdk version: 1.8

**Comment by magnolia-k** [comment]
Using Jackson is more appropriate in terms of a more correct JSON parser.

Currently, there are not enough resources to lift the native version to a more correct parser behavior, but the patch is welcome.
