### ISSUE TITLE
Extracting with type hints can produce object of wrong type

### ISSUE THREAD

**Issue by asantas93** [json4s/json4s#617]
### json4s version
3.6.7 (tested with jackson and native)
### scala version
2.12
### jdk version
8
### Description
When using type hints, I can extract an object of the wrong type as shown below. I expect some kind of exception saying the object had the type hint for another class, or that the JSON didn't have the necessary fields (`bar`) to construct my object.

```scala
import org.json4s.jackson.{JsonMethods, Serialization}
import org.json4s.{DefaultFormats, Formats, TypeHints}
import org.scalatest.FlatSpec

class TypeHintTest extends FlatSpec {

  implicit val formats: Formats = DefaultFormats + MyTypeHints

  it should "fail to deserialize wrong type" in {
    val dump = Serialization.write(Foo(1))
    assertThrows[Throwable] {
      println(JsonMethods.parse(dump).extract[Bar])
    }
  }

}

trait MyTrait
case class Foo(foo: Int) extends MyTrait
case class Bar(bar: String) extends MyTrait

object MyTypeHints extends TypeHints {
  override val hints: List[Class[_]] = List(classOf[Foo], classOf[Bar])

  override def hintFor(clazz: Class[_]): String = Map[Class[_], String](
    classOf[Foo] -> "foo",
    classOf[Bar] -> "bar",
  )(clazz)

  override def classFor(hint: String): Option[Class[_]] = Map[String, Class[_]](
    "foo" -> classOf[Foo],
    "bar" -> classOf[Bar],
  ).get(hint)
}
```

Fails, printing `Foo(1)`

**Comment by magnolia-k** [comment]
If I rewrite the code as follows, the exception was pronounced correctly and the test passed.

before:
```scala
println(JsonMethods.parse(dump).extract[Bar])
```

after:
```scala
val parsed = JsonMethods.parse(dump)
val extracted = parsed.extract[Bar]
println(extracted)
```

**Comment by magnolia-k** [comment]
The erasure has been replaced with the class found in typeHints, but at this time the consistency with the type specified in extract has not been checked.

https://github.com/json4s/json4s/blob/e776c4e639860439b5d6ad52a87e5df95f6a9bf9/core/src/main/scala/org/json4s/Extraction.scala#L663-L665

**Comment by asantas93** [comment]
@magnolia-k Thank you for posting this workaround! I'm blown away that creating an intermediate `val` changes behavior. Can you explain why that changes which code path ends up executing?

**Comment by asantas93** [comment]
Attempting to answer my own question: seems like the issues is wrapping the `extract` call in a method which doesn't require the extracted object to be type given to `extract`, i.e. if I have
```scala
def printMyTrait(o: MyTrait) = println(o)
def printBar(o: Bar) = println(o)
```
then 
```scala
printBar(JsonMethods.parse(dump).extract[Bar])
```
throws an exception but
```scala
printMyTrait(JsonMethods.parse(dump).extract[Bar])
```
does not.

**Comment by magnolia-k** [comment]
I checked the test execution results and found that the last println was not executed in my example.

**Comment by asantas93** [comment]
Opened https://github.com/json4s/json4s/pull/698 with potential solution.

**Comment by asantas93** [comment]
This issue should be fixed with that PR merged. Is it possible to publish `3.7.0-M6` soon? @mccartney @magnolia-k

**Comment by asantas93** [comment]
Confirmed this is no longer an issue for me in 3.7.0-M6
