### ISSUE TITLE
Throwing MappingException within CustomSerializer results in cryptic exception

### ISSUE THREAD

**Issue by flonso** [json4s/json4s#618]
### json4s version
3.6.0 and above
### scala version
2.12.7 (but probably irrelevant)
### jdk version
openjdk version "1.8.0_212"

### Offending commit :
 https://github.com/json4s/json4s/commit/243da5b2e16e3a088dd05f91a2eb162290137ae5
### Offending line :
https://github.com/json4s/json4s/blob/8bb230ecc3865dc866811257445b6296d73213ca/core/src/main/scala/org/json4s/Extraction.scala#L567

## The problem
If a `MappingException` is thrown in the `try` section of `Extraction.buildCtorArg`, the related `catch` clause will attempt an extraction of `Null` which can fail with a cryptic message and make debugging pretty hard (since we lose all the information that was present in the original `MappingException`).

## Example 
```scala
import org.json4s.JsonAST.{ JField, JObject, JString }
import org.json4s.jackson.Serialization
import org.json4s.{ CustomSerializer, DefaultFormats, Extraction, MappingException }


object MyTest {

  case class MyClass(name: String)
  case class Test(value: Option[MyClass])

  object MyFormats extends DefaultFormats {
    override val strictOptionParsing = true
  }


  object MyClassSerializer extends CustomSerializer[MyClass](
    implicit formats => (
      {
        case obj: JObject => MyClass(
          name = obj \ "name" match {
            case JString(value) if value == "valid" => value
            case value => throw new MappingException(s"No valid value found for name (found $value)")
          }
        )
      },
      {
        case c: MyClass => JObject(
          List(
            JField("name", Extraction.decompose(c.name))
          )
        )
      }
    )
  )

  def main(args: Array[String]): Unit = {
    implicit val formats = MyFormats + MyClassSerializer

    val json = """{"value":{"name": "invalid"}}"""

    // Fails with exception
    val read = Serialization.read[Test](json)
    println(read)
  }
}
```
Exception thrown : `Exception in thread "main" org.json4s.package$MappingException: No constructor for type Null$, JObject(List((name,JString(invalid))))`

## How it should behave:
The thrown MappingException should be preserved:
`Caused by: org.json4s.package$MappingException: No valid value found for name (found JString(invalid))`

## Proposed solution
Wrap the test `extract(json, ScalaType[Null](implicitly)) == null` in a `try-catch` which returns `false` if an exception is thrown and the result of the equality otherwise.

```scala
lazy val nullCheck = try {
  extract(json, ScalaType[Null](implicitly)) == null
} catch {
  case _: Throwable => false
}
// And the condition becomes
!formats.strictOptionParsing || nullCheck
```

**Comment by magnolia-k** [comment]
I made PR.

https://github.com/json4s/json4s/pull/643

**Comment by flonso** [comment]
Great thanks ! 

Any idea when it is going to be merged/released in a new version ?

**Comment by magnolia-k** [comment]
@seratch @xuwei-k 

What are the release milestones for Json4s 3.7.0?

**Comment by seratch** [comment]
@magnolia-k I can work on it.

**Comment by seratch** [comment]
I was going to release version 3.7.0-M2 but somehow publish operations did go well. I'm afraid there is something wrong with the Sonatype OSS repositories at the moment. 🤔

**Comment by seratch** [comment]
Done.

**Comment by magnolia-k** [comment]
thanks!

@flonso 

Problem solved?
Can this issue be closed?

**Comment by flonso** [comment]
Indeed problem solved, thanks a lot !
