### ISSUE TITLE
json4s.org domain expired?

### ISSUE THREAD

**Issue by xuwei-k** [json4s/json4s#630]

**Comment by rossabaker** [comment]
I don't remember anyone ever registering that domain, and can't find any registrar notices in my email archive. I don't know who owned that. Sorry.

**Comment by casualjim** [comment]
I own it
I'll fix it

**Comment by casualjim** [comment]
I had to redeem the domain, apparently that's going to take a while

**Comment by casualjim** [comment]
in the mean time this url still works though: https://json4s.github.io/json4s/

**Comment by casualjim** [comment]
interesting the domain is active again but it doesn't end up at the right site

**Comment by casualjim** [comment]
It started working now. http://json4s.org

**Comment by xuwei-k** [comment]
👍

**Comment by xuwei-k** [comment]
https://who.is/whois/json4s.org

> Expires On 2020-08-27

😢

**Comment by magnolia-k** [comment]
Updated

> 2021-11-14
