### ISSUE TITLE
Serialization interface with access to deeper type information

### ISSUE THREAD

**Issue by asantas93** [json4s/json4s#631]
### json4s version
3.6.7
### scala version
2.12
### jdk version
8

`Serializer` is given insufficient information to deserialize a container class with type arguments who themselves have type arguments. Concrete example:

```scala
import org.json4s.Extraction._
import org.json4s.JsonAST.JArray
import org.json4s.reflect.TypeInfo
import org.json4s.{Formats, JValue, Serializer}

class Tuple2Serde extends Serializer[(_, _)] {

  override def deserialize(implicit format: Formats): PartialFunction[(TypeInfo, JValue), (_, _)] = {
    case (TypeInfo(clazz, Some(paramType)), JArray(values)) if classOf[(_, _)] == clazz =>
      val typeArgs = paramType.getActualTypeArguments
      (extract(values.head, TypeInfo(typeArgs.head.asInstanceOf[Class[_]], None)),
        extract(values(1), TypeInfo(typeArgs(1).asInstanceOf[Class[_]], None)))
  }

  override def serialize(implicit format: Formats): PartialFunction[Any, JValue] = {
    case t: (_, _) => JArray(t.productIterator.map(decompose).toList)
  }
}
```
As far as I can tell, there is no suitable information in `paramType` to use in place of `None` when calling `extract` with `TypeInfo` for the tuple's enclosed values. If we had access to a `universe.Type` or some other deeper type information, it would be possible to do this deserialization without loss of type information.

**Comment by asantas93** [comment]
Prototype PR: https://github.com/json4s/json4s/pull/632

**Comment by magnolia-k** [comment]
@asantas93 
Can I close this issue anymore?

**Comment by asantas93** [comment]
I think I found a bug, but I can report that separately if you want to close this.

**Comment by magnolia-k** [comment]
@asantas93 

Since the PR has already been merged and released, I think it is better to raise another issue.
