### ISSUE TITLE
MonadicJValue replace not working according to documentation

### ISSUE THREAD

**Issue by TomasAndersen** [json4s/json4s#636]
### json4s version
3.5.3
### scala version
2.11.12
### jdk version
8

According to documentation in MonadicJValue:
https://github.com/json4s/json4s/blob/4628700814624ba71aca2c9eadba12c15a628aa1/core/src/main/scala/org/json4s/MonadicJValue.scala#L216

it should be possible to replace values for arrays either by index or all matching. This is not working.
I am running the following code:
`          val test1 = JObject(List(JField("foo", JObject(List(JField("bar", JInt(1))))))).replace("foo" :: "bar" :: Nil, JString("baz"))`
`          val test2 = JObject(List(JField("foo", JArray(List(JObject(List(JField("bar", JInt(1)))), JObject(List(JField("bar", JInt(2))))))))).replace("foo[]" :: "bar" :: Nil, JString("baz"))`
`         val test3 = JObject(List(JField("foo", JArray(List(JObject(List(JField("bar", JInt(1)))), JObject(List(JField("bar", JInt(2))))))))).replace("foo[0]" :: "bar" :: Nil, JString("baz"))
`

Only test1 is set as documented.
The two others involving a JArray keeps to old value.

**Comment by TomasAndersen** [comment]
I have also tried this with the latest version (3.6.7) with the same result

**Comment by TomasAndersen** [comment]
I found a workaround but would prefer the replace function to work as specified:

`  private def jsonFieldUpdater(json: JValue, list: List[Map[String, JValue]]): JValue =
    list.foldLeft(json) { case (json, kvs) => {
      kvs.foldLeft(json) { case (json, (key, value)) => {
        if (value.isInstanceOf[JArray]) {
          val sti = key.split("[.]").toList
          val groupKey = sti.dropRight(1).last

          val replacedJson = json mapField {
            case (groupKey, JArray(arr)) => (groupKey, value)
            case other => other
          }

          replacedJson
        } else {
          val replacedJson = json.replace(key.split("[.]").toList, value)
          replacedJson
        }
      }
      }
    }
    }`

**Comment by magnolia-k** [comment]
@TomasAndersen 

That feature is supported since 3.7.0, see commit below.

https://github.com/json4s/json4s/commit/be2551ae518f003c59494bf72a212fb7f6d2ff42

Try with version 3.7.0-M1.

**Comment by magnolia-k** [comment]
@TomasAndersen 

solved the problem?
Can this issue be closed?

**Comment by TomasAndersen** [comment]
Hi. Thanks @magnolia-k . I tested with 3.7.0-M2 and this resolves the problem. Thanks.
