### ISSUE TITLE
Breaking change on case class constructor params discovery

### ISSUE THREAD

**Issue by AlexisBRENON** [json4s/json4s#637]
# Versions
 * json4s version: json4s-jackson % 3.5.3
 * scala version: 2.12.8
 * jdk version: 1.8.0

# What is the current behavior

While trying to serialize a case class instance to JSON, I got an empty object `{}`. Debugging led me to the `Extraction.decomposeObject` method. Here the `descriptor` variable has a `constructors` field, with one constructor in it represented as `ConstructorDescriptor(List(),Executable(Constructor(public Param(java.lang.String,scala.Option))),false)` and an empty `params` list.

# What is the expected behavior

With version json4s-jackson % 3.2.11, the object is correctly serialized. In `decomposeObject`, `descriptor.constructors[0]` is `ConstructorDescriptor(ArrayBuffer(ConstructorParamDescriptor(key,key,0,String,Some(<function0>)), ConstructorParamDescriptor(value,value,1,Option[TypedValue],Some(<function0>))),public Param(java.lang.String,scala.Option),false)`

# More informations

Some other similar case classes (protobuf classes) are serialized correctly.
I am working on a minimal faulty example.

**Comment by AlexisBRENON** [comment]
Some more informations.

The case class that I try to serialize is a protobuf class, generated with [scalapb](https://scalapb.github.io/).
I tried with a similar class but written by hand (just class definition) and it works as expected.
I upgraded both, scalapb (to 0.9.4) and json4s-jackson (to 3.7.0-M1) but I am still unable to serialize my protobuf class.

While trying to debug, I finally arrive to the [line 156 in `org/json4s/reflect/Reflector.scala`](https://github.com/json4s/json4s/blob/v3.7.0-M1/core/src/main/scala/org/json4s/reflect/Reflector.scala#L156) that is preceeded by the comment: `# maybe impossible`.
So I suppose that this is not expected to happen...

This happens because on [line 141](https://github.com/json4s/json4s/blob/v3.7.0-M1/core/src/main/scala/org/json4s/reflect/Reflector.scala#L141), the `paramNameReader` raised an exception.

**Comment by AlexisBRENON** [comment]
Here is the proto messages. A single `TypedValue` can be serialized without any problem, but I cannot serialize a `Param`.
```proto
syntax = "proto3";

package foo.hyper_optimization.v1;

message TypedValue {
    oneof value {
        double double = 1;
        int32 int = 2;
        bool bool = 3;
    }
}

message Param {
    string key = 1;
    TypedValue value = 2;
}
```

**Comment by magnolia-k** [comment]
@AlexisBRENON Is it possible to show the smallest reproducible code set?

An example of only the protocol buffer is shown, but if you have a complete set of sbt project files it will be easier to analyze

**Comment by AlexisBRENON** [comment]
I think it was a version mismatch between `json4s` and `paranamer`.
I didn't reproduce the error with a minimal reproducible example, using `json4s 3.5.3` which depends on  `paranamer 2.8`.
