### ISSUE TITLE
Is the dependency on paranamer unnecessary?

### ISSUE THREAD

**Issue by magnolia-k** [json4s/json4s#645]
json4s depends on paranamer, but it seems that the equivalent function has been introduced in Java8, so it can be removed.

https://github.com/paul-hammant/paranamer

https://stackoverflow.com/questions/21455403/how-to-get-method-parameter-names-in-java-8-using-reflection

**Comment by mccartney** [comment]
Ah. Now I can see in https://github.com/json4s/json4s/blob/master/CONTRIBUTING.md that in 3.5 and master we require Java 8:
> This branch requires Java 8+ for all Scala versions
So my previous comment is wrong.

**Comment by magnolia-k** [comment]
I don't have time to fix it now, but I'd really like to.
