### ISSUE TITLE
Question about default values

### ISSUE THREAD

**Issue by tjarvstrand** [json4s/json4s#649]
### json4s version
3.6.7
### scala version
2.12
### jdk version
1.8

Hi I have a question about default values in case classes. I'm having trouble setting a default value for a `Map` value when the input contains an explicit `null`-value. Here's a test to demonstrate:
```
import org.json4s.Formats
import org.json4s.NoTypeHints
import org.json4s.native.Serialization
import org.scalatest.FlatSpec

case class IntClass(v: Int = 0)
case class MapClass(v: Map[String, String] = Map.empty)

class Json4sTest extends FlatSpec{
  implicit val formats: Formats = Serialization.formats(NoTypeHints)

  // This passes
  "IntClass" should "deserialize with default when value is missing" in {
    assert(Serialization.read[IntClass]("""{}""").v === 0)
  }

  // This passes
  it should "deserialize with default when value is null" in {
    assert(Serialization.read[IntClass]("""{"v": null}""").v === 0)
  }

  // This passes
  "MapClass" should "deserialize with default when value is missing" in {
    assert(Serialization.read[MapClass]("""{}""").v === Map.empty)
  }

  // This Fails!
  it should "deserialize with default when value is null" in {
    assert(Serialization.read[MapClass]("""{"v": null}""").v === Map.empty)
  }
}
```

Is there any way I can use a default value for the `Map` in this case?

**Comment by magnolia-k** [comment]
@tjarvstrand 

Test "deserialize with default when value is null" does not match Int with `{"v": null}`, so the default value is used.

But test "deserialize with default when value is null" fails because trying to apply JNull to `Map[String, String]` values (null is not allowed).

**Comment by magnolia-k** [comment]
The basic behavior of Json4s is that extra fields are ignored when mapping to objects.

**Comment by magnolia-k** [comment]
@tjarvstrand 
solved the problem? If you have another problem, open a new issue again.

**Comment by tjarvstrand** [comment]
Hey @magnolia-k Sorry for the delay!

I'd like to be able to treat `null` as a missing value and fall back to the default value. Is that possible?

**Comment by tjarvstrand** [comment]
Hm, I don't understand the thumbs up :smile: 

Does that mean it's possible? How?

**Comment by kondaurovDev** [comment]
I think you need to setup  **extractionNullStrategy**

	implicit val defaultFormats: DefaultFormats = new DefaultFormats {
		override val extractionNullStrategy: ExtractionNullStrategy = ExtractionNullStrategy.TreatAsAbsent
	}

```
object ExtractionNullStrategy {

  /**
   * Default behaviour - keep null values
   */
  case object Keep extends ExtractionNullStrategy

  /**
   * Fail if null values are encountered
   */
  case object Disallow extends ExtractionNullStrategy

  /**
   * Filters out null values, as if they were not present
   */
  case object TreatAsAbsent extends ExtractionNullStrategy
}

sealed abstract class ExtractionNullStrategy extends Product with Serializable
```

**Comment by tjarvstrand** [comment]
@kondaurovDev Thanks :D

The `TreatAsAbsent` option was added (by me) after this issue
