### ISSUE TITLE
Incompatibility with scala-parallel-collections from scala-lang

### ISSUE THREAD

**Issue by cchafer** [json4s/json4s#660]
### jdk version 8 / 11

Before scala 2.13, parallel collections were included in the langage.
Now, one needs to add scala-parallel-collections as a dependency to get parallel operations.
But adding this dependency breaks extraction of sequences.

### Reproduction
build.sbt:
```
scalaVersion := "2.13.1"
libraryDependencies ++= Seq(
  "org.json4s" %% "json4s-core" % "3.6.7",
  "org.json4s" %% "json4s-jackson" % "3.6.7",
  "org.scala-lang.modules" %% "scala-parallel-collections" % "0.2.0"
)
```
scala test code:
```
import org.json4s.DefaultFormats
import org.json4s.jackson.JsonMethods

final case class Foo(s: Seq[Any])

object TestJson4s extends App {
  val json = """{"s":[]}"""
  val foo = JsonMethods.parse(json).extract(DefaultFormats, manifest[Foo])
  println(foo)
}
```

Running this will generate this exception: 
```
Caused by: java.lang.NoSuchMethodException: scala.collection.immutable.Seq$.apply(scala.collection.Seq)
```

The reason is that scala-parallel-collections adds in the classpath the interface ***scala.collection.generic.GenericTraversableTemplate*** which is then used in org.json4s.Extraction:473.

**Comment by firehooper** [comment]
@cchafer  I put in a pull request for the fix you can publish locally if you need it still
