### ISSUE TITLE
Provide option to ignore apply functions at de-serialization time

### ISSUE THREAD

**Issue by BlueTufa** [json4s/json4s#663]
For applications using Json4s prior to Json 3.6, there are are scenarios which have apply functions in place that were never intended for use for Json de-serialization.  Upgrading to Json4s 3.6 and up causes these apply functions to be used for de-serialization, sometimes in a non-deterministic way.  This will occasionally result in runtime failures.  

Requesting a configuration option to disable usage of apply functions for de-serialization purposes.  

A thoughtful solution to this request may also address the following issue:
https://github.com/json4s/json4s/pull/487

### json4s version
3.6.7+

### scala version
2.12.8+

### jdk version
Java 8+

**Comment by BlueTufa** [comment]
My team is currently planning to submit a PR to address this.

**Comment by mccartney** [comment]
Solved by #667.
