### ISSUE TITLE
Enable Scala Steward for this repo

### ISSUE THREAD

**Issue by mccartney** [json4s/json4s#676]
I suggest to sign up this repository for Scala Steward - a bot which suggests PRs with dependency upgrades:
https://github.com/fthomas/scala-steward

Quick-start is easy.

**Comment by mccartney** [comment]
I can help configuring it once the idea is approved by project maintainers.

**Comment by mccartney** [comment]
@xuwei-k would you be interested?

**Comment by magnolia-k** [comment]
Since the Scala Steward has already been enabled, this issue is closed.
