### ISSUE TITLE
Make sure Travis builds branch-merged-to-master for PRs

### ISSUE THREAD

**Issue by mccartney** [json4s/json4s#697]
An internal issue with repo configuration. Make sure Travis CI builds the code of "branch of this PR put on latest master". I think at the time it only builds just the branch.

**Comment by mccartney** [comment]
Hmmm. It seems like it's on:
<img width="401" alt="image" src="https://user-images.githubusercontent.com/762437/85896334-9488ff00-b7f8-11ea-8ad5-9cf7ae52c585.png">

**Comment by mccartney** [comment]
@seratch do we have this turned on in Github?
https://github.com/json4s/json4s/settings/branches | master

![image](https://user-images.githubusercontent.com/762437/85915644-94651f80-b849-11ea-8bfc-89d5939d4949.png)

**Comment by seratch** [comment]
@mccartney We hadn't turned it on, but I agree that enabling it is much better for safety. I just updated the branch settings for the `master` branch. From my past experiences, the setting change may not be applied to already existing PRs, but the forthcoming ones should get the benefit.

**Comment by seratch** [comment]
Happily, it seems to be working for existing ones. We're all set!

<img width="500" src="https://user-images.githubusercontent.com/19658/85916109-5affd480-b888-11ea-8635-8b2092416a4a.png">

**Comment by mccartney** [comment]
Thank you and sorry for the trouble :)
