### ISSUE TITLE
Jackson JsonMethods allows override of `mapper` but Serialization uses default JsonMethods

### ISSUE THREAD

**Issue by LannyRipple** [json4s/json4s#710]
### json4s version
latest

### scala version
any

### jdk version
8

### Description
We wish to use json4s Serialization with Jackson using a custom configured ObjectMapper.  Jackson allows an override on `mapper` for JsonMethods but provides no mechanism for providing a custom JsonMethods in Serialization (which uses the default Jackson JsonMethods).

**Comment by mccartney** [comment]
Solved in #711
