### ISSUE TITLE
Does DSL example in the readme.md still work?

### ISSUE THREAD

**Issue by oneengineer** [json4s/json4s#713]
### json4s version
3.6.9
### scala version
2.13.2
### jdk version
11.0

```
import org.json4s
import org.json4s._
import org.json4s.native.JsonMethods._
import org.json4s.JsonDSL._

render(compact(List(1,2,3)))

```

it complains:

Error:(15, 22) type mismatch;
 found   : List[Int]
 required: org.json4s.native.Document
  render(compact(List(1,2,3)))

However `val x:json4s.JArray = List(1,2,3)` still work

**Comment by xuwei-k** [comment]
I think you made a mistake.

```diff
- render(compact(List(1,2,3)))
+ compact(render(List(1,2,3)))
```
