### ISSUE TITLE
camelizeKeys throws StringIndexOutOfBoundsException if key has double underscores

### ISSUE THREAD

**Issue by tabdulradi** [json4s/json4s#714]
### json4s version
Tested on 3.6.5 and master, but I suspect it fails on more versions
### scala version
2.12
### jdk version
8

Here is a test case to expose the error https://github.com/json4s/json4s/pull/715 search [the logs](https://travis-ci.com/github/json4s/json4s/jobs/376070026) for 

> java.lang.StringIndexOutOfBoundsException: String index out of range: 1 (MonadicJValue.scala:377)

**Comment by mccartney** [comment]
Fixed in #715. Thanks for reporting and fixing.
