### ISSUE TITLE
Deserialize JSON fails with hyphen in key 

### ISSUE THREAD

**Issue by laballab** [json4s/json4s#716]
### json4s version
`"json4s-jackson" % "3.7.0-M6"`

### scala version
`scalaVersion := "2.12.12"`

### jdk version
`AdoptOpenJDK Java 11.0.6`

With the following model:
```
case class Test(
  testVal: String
)
```

Attempting to deserialize this message:
```
import org.json4s._
import org.json4s.jackson.JsonMethods._

implicit val formats: Formats = DefaultFormats

parse("""{ "test-val": "one" }""").camelizeKeys.extract[Test]
```

fails with:
```
[error] (run-main-0) org.json4s.package$MappingException: No usable value for testVal
[error] Did not find value which can be converted into java.lang.String
```

Whereas one without hyphens deserializes without problem:
```
parse("""{ "test_val": "one" }""").camelizeKeys.extract[Test]
```

Not sure why this is failing with the jackson backend as jackson objectMapper can deserialize similar messages/models without issues. 

Appreciate the feedback.

**Comment by tjarvstrand** [comment]
This is not in the parsing but in the extraction and has to do with how json4s maps keys to member names. There is a hint in the README:

>By default the constructor parameter names must match json field names. However, sometimes json field names contain characters which are not allowed characters in Scala identifiers. ...

Try reading from there

**Comment by magnolia-k** [comment]
@laballab 
Have you solved this problem?
I'm closing this issue, but if it's not resolved, please reopen it.
