### ISSUE TITLE
strictOptionParsing requires optional values to be present

### ISSUE THREAD

**Issue by tjarvstrand** [json4s/json4s#730]
### json4s version
v3.7.0-M7

### scala version
2.13.3

### jdk version
13.0.2

### Observed behaviour
Currently the `strictOptionParsing`-setting requires values to be present even if they are typed as optional.

### Expected behaviour
Fields specified as optional, eg. `case class X(v: Option[Int])`, should be extracted as `None` if missing, even with `strictOptionParsing` enabled

**Comment by magnolia-k** [comment]
As I commented in the PR, it is very difficult to understand how strictOptionParsing is affected by the class definition and data status.
If possible, it would be great if you could add a table to the README that summarizes the behavior.
