### ISSUE TITLE
Adding field serializer should use manifest from FieldSerializer object

### ISSUE THREAD

**Issue by mpartel** [json4s/json4s#74]
I just debugged a case where I had assigned my `FieldSerializer[Foo]` to a variable typed `FieldSerializer[_]` before adding it to `Formats`. The `+` operator got a `Manifest[java.lang.Object]`, and a spectacular crash followed later.

If the `+` operator used the manifest that was given when `FieldSerializer` was built, such a mistake would not be possible. Then we could also add:

```
def ++ (newSerializers: Traversable[FieldSerializer[_]]): Formats
```

for symmetry with the other `++`. I had wondered why there wasn't one. Now I think I know :-)

**Comment by maniax89** [comment]
is there any way to add multiple `FieldSerializer`s without chaining `implicit val formats = DefaultFormats + FieldSerializer[One]() + FieldSerializer[Two]() + FieldSerializer[Three]()` ?
