### ISSUE TITLE
scala 3 status 

### ISSUE THREAD

**Issue by bchazalet** [json4s/json4s#743]
It looks like the CI is already building master against scala 3.0.0-M3, does that mean json4s is ready for scala 3? If so, could it be possible to publish v3.7.0-M7 against scala 3 so that downstream libraries (I'm thinking of squeryl for example), could start using it to prepare their own releases for scala 3?

If it is not ready for scala 3, what's missing and do you need some help to make it ready?

**Comment by magnolia-k** [comment]
Scala3 does not provide the same runtime reflection features as Scala2, so Json4s that use runtime reflection for object creation will need significant modifications to be compatible with Scala3.

Currently, the only part of the AST that is CI'd for Scala3 is the part that does not use runtime reflection.

**Comment by bchazalet** [comment]
thanks for the response @magnolia-k. Am right to assume that the whole scalap subproject will have no equivalent in scala 3 then?

**Comment by magnolia-k** [comment]
There's currently no way to create an object using a constructor symbol.
There is a way to get class information at compile time, but it needs to be completely rewritten.

**Comment by bchazalet** [comment]
thanks for the info! I'm closing this then.

**Comment by xuwei-k** [comment]
- https://github.com/json4s/json4s/pull/1460
