### ISSUE TITLE
Not all unicodes are escaped, even when using alwaysEscapeUnicode: Boolean = true

### ISSUE THREAD

**Issue by toshetah** [json4s/json4s#750]
### jdk version 1.8

This is how to reproduce:

```
implicit val customJsonFormats = new DefaultFormats {
  override def alwaysEscapeUnicode: Boolean = true
}

println(pretty(render(JString("€"))))
```

**Comment by magnolia-k** [comment]
The native version and the jackson version behave differently.

```scala
scala> import org.json4s._
import org.json4s._

scala> import org.json4s.native.JsonMethods._
import org.json4s.native.JsonMethods._

scala> implicit val customJsonFormats = new DefaultFormats {
     |   override def alwaysEscapeUnicode: Boolean = true
     | }
     |
val customJsonFormats: org.json4s.DefaultFormats = $anon$1@4137e49

scala> println(pretty(render(JString("€"))))
     |
"\u20ac"
```

```scala
scala> import org.json4s._
import org.json4s._

scala> import org.json4s.jackson.JsonMethods._
import org.json4s.jackson.JsonMethods._

scala> implicit val customJsonFormats = new DefaultFormats {
     |   override def alwaysEscapeUnicode: Boolean = true
     | }
val customJsonFormats: org.json4s.DefaultFormats = $anon$1@90e49f9

scala> println(pretty(render(JString("€"))))
"€"
```

**Comment by magnolia-k** [comment]
In the current Json4s, the setting to escape UNICODE is not enabled on the jackson module.

The following code will solve the problem.

```scala
scala> import org.json4s._
import org.json4s._

scala> import org.json4s.jackson.JsonMethods._
import org.json4s.jackson.JsonMethods._

scala> implicit val customJsonFormats = new DefaultFormats {
     |   override def alwaysEscapeUnicode: Boolean = true
     | }
val customJsonFormats: org.json4s.DefaultFormats = $anon$1@1a26022e

scala> import com.fasterxml.jackson.core.json._
import com.fasterxml.jackson.core.json._

scala> org.json4s.jackson.JsonMethods.mapper.getFactory().configure(JsonWriteFeature.ESCAPE_NON_ASCII.mappedFeature(), true);
val res1: com.fasterxml.jackson.core.JsonFactory = com.fasterxml.jackson.databind.MappingJsonFactory@58e3ef2d

scala> println(pretty(render(JString("€"))))
"\u20AC"
```
In the render method of `json4s-jackson`, code should be added to determine whether or not to set `JsonWriteFeature.ESCAPE_NON_ASCII` based on the value of `alwaysEscapeUnicode`.

**Comment by magnolia-k** [comment]
Note that the current € symbol is always escaped, regardless of the setting.

This feature is probably not appropriate.
```scala
scala> import org.json4s._
import org.json4s._

scala> import org.json4s.native.JsonMethods._
import org.json4s.native.JsonMethods._

scala> implicit val customJsonFormats = new DefaultFormats {
     | override def alwaysEscapeUnicode: Boolean = false
     | }
val customJsonFormats: org.json4s.DefaultFormats = $anon$1@67612481

scala> println(pretty(render(JString("€"))))
"\u20ac"
```
The code to determine the target of escaping is as follows, but it is excessive.

```scala
            (c >= '\u0000' && c <= '\u001f') || (c >= '\u0080' && c < '\u00a0') || (c >= '\u2000' && c < '\u2100')
```

**Comment by toshetah** [comment]
> In the current Json4s, the setting to escape UNICODE is not enabled on the jackson module.
> 
> The following code will solve the problem.
> 
> ```scala
> scala> import org.json4s._
> import org.json4s._
> 
> scala> import org.json4s.jackson.JsonMethods._
> import org.json4s.jackson.JsonMethods._
> 
> scala> implicit val customJsonFormats = new DefaultFormats {
>      |   override def alwaysEscapeUnicode: Boolean = true
>      | }
> val customJsonFormats: org.json4s.DefaultFormats = $anon$1@1a26022e
> 
> scala> import com.fasterxml.jackson.core.json._
> import com.fasterxml.jackson.core.json._
> 
> scala> org.json4s.jackson.JsonMethods.mapper.getFactory().configure(JsonWriteFeature.ESCAPE_NON_ASCII.mappedFeature(), true);
> val res1: com.fasterxml.jackson.core.JsonFactory = com.fasterxml.jackson.databind.MappingJsonFactory@58e3ef2d
> 
> scala> println(pretty(render(JString("€"))))
> "\u20AC"
> ```
> 
> In the render method of `json4s-jackson`, code should be added to determine whether or not to set `JsonWriteFeature.ESCAPE_NON_ASCII` based on the value of `alwaysEscapeUnicode`.

You can see in your example that it doesn't work. Basically what I understand from your answers, is that it is basically impossible at the moment with json4s native. Only using jackson.

**Comment by toshetah** [comment]
Is there any plan to fix this?

**Comment by magnolia-k** [comment]
I made PR.

https://github.com/json4s/json4s/pull/752

this PR is merged, escaping in Jackson should work correctly.

**Comment by toshetah** [comment]
Thank you! When is that going to be released?
