### ISSUE TITLE
Infinite loop with type alias to primitive

### ISSUE THREAD

**Issue by rossabaker** [json4s/json4s#76]
I don't have a minimized test case yet, but I do have an offending line:

https://github.com/json4s/json4s/blob/v3.2.5_2.10/core/src/main/scala/org/json4s/reflect/ScalaSigReader.scala#L121

The other pattern matches have `case TypeRef(_, symbol, Nil) => symbol`.  Is that acceptable here?

**Comment by lightvector** [comment]
Also ran into this bug, getting an infinite loop that went away after I removed some aliases for primitive types used in case class fields.

**Comment by magnolia-k** [comment]
This issue is closed because the discussion of this issue continues at # 397.
