### ISSUE TITLE
"org.json4s" % "json4s-core_3.0.0-RC2" % "3.7.0-M15" not published in maven central

### ISSUE THREAD

**Issue by SaadKhawaja** [json4s/json4s#784]
### json4s version
3.7.0-M15

### scala version
3.0.0-RC2

### jdk version
Not applicable.

The **"org.json4s" % "json4s-core_3.0.0-RC2" % "3.7.0-M15"** library is not published in maven.  The corresponding modules for same version are available.  Issue happens because **org.json4s:json4s-jackson_3.0.0-RC2:3.7.0-M15** has dependency on this.  Also preventing projects from using the features in json4s-core.  
Thanks

**Comment by xuwei-k** [comment]
https://repo1.maven.org/maven2/org/json4s/json4s-core_3.0.0-RC2/
