### ISSUE TITLE
Default implementation for readEither, deprecating read

### ISSUE THREAD

**Issue by thesamet** [json4s/json4s#789]
### json4s version
3.7.0-M16

### scala version
2.13/3.0

3.7.x recently added an abstract `Reader.readEither`. Existing implementations of `Reader` break: (`object creation impossible. Missing implementation for: ... def readEither`) and library users need to implement both `read` and `readEither` which overlap up to how they handle errors. Would it make sense to mark `read` as deprecated? Should one of them have a default implementation in terms of the other provided by json4s?

**Comment by xuwei-k** [comment]
pull requests welcome 😃

**Comment by thesamet** [comment]
Resolved via #796
