### ISSUE TITLE
Major version bump?

### ISSUE THREAD

**Issue by thesamet** [json4s/json4s#797]
I ran a mima check on scalapb-json4s and noticed a bunch of binary incompatibilities coming through ScalaPB-json4s public methods through the 3.7.0-RC1 upgrade. Specifically, methods that used to return  `org.json4s.JsonAST#JValue` now return `org.json4s.JValue`

Also, given that the upcoming version encourages using `Either` over exceptions, I wonder if a major version bump is due to communicate those breaking changes? See "Recommended version scheme" on https://docs.scala-lang.org/overviews/core/binary-compatibility-for-library-authors.html

**Comment by xuwei-k** [comment]
https://github.com/json4s/json4s/releases/tag/v4.0.0

4.0.0 released

**Comment by michael-etzkorn** [comment]
@xuwei-k is there a recommended way to do this sort of conversion now then? I noticed a project I use broke when upgrading to version 4, but I can't find documentation about the API changes. 

https://github.com/chipsalliance/treadle/blob/master/src/main/scala/treadle/executable/DataStore.scala#L490-L501

I noticed there were some changes [here](https://github.com/json4s/json4s/blob/32f486529ed942254943d70f81cd7359725ea678/ast/src/main/scala/org/json4s/JsonDSL.scala#L70-L74) that seem relevant. I'm still relatively new to Scala so apologies if the fix seems straightforward. Appreciate the help!
