### ISSUE TITLE
Provide Parent/Child example with a back reference to the parent

### ISSUE THREAD

**Issue by awhitford** [json4s/json4s#80]
I am interested in seeing an example of representing a Parent/Child relationship where the Child has a reference to the Parent:

``` scala
  case class Parent (name: String, children: List[Child])
  case class Child(name: String, parent: Parent)
```

Also, a self-referencing (and non-infinite-looping) example:

``` scala
  case class Person(name: String, parent: Option[Person], children: List[Person])
```

**Comment by magnolia-k** [comment]
There have been no other requests for a long time, so if this is still an issue, please raise an issue again.
